### ISSUE TITLE
livemint.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#10]
http://www.livemint.com/Consumer/UtSiZipRS4yqHSZlhEVIPP/Rio-Olympics-That-sinking-feeling.html

**Comment by X01X012013** [comment]
Thank you for your report, the fix is patched into 1.0.70. 

`setReadOnly("canRun1", true);`

**Comment by X01X012013** [comment]
There is no update for 5 days, I assume the fix worked.
