### ISSUE TITLE
Unable to install userscript in Tampermonkey!

### ISSUE THREAD

**Issue by CrescentEclipse** [X01X012013/AdBlockProtector#100]
Hi. I can't install the userscript in Tampermonkey 4.3.5384. It displays an error "wrong syntax".
What am I doing wrong?

**Comment by X01X012013** [comment]
I'm not sure how you got Tampermonkey 4.3, since the newest version in Chrome extension store is 4.2. Can you tell me which browser are you using, and how did you try to install Script?

**Comment by CrescentEclipse** [comment]
I am using firefox. I just went to the mozilla site and installed it.
https://addons.mozilla.org/de/firefox/addon/tampermonkey/

I tried to just click on the userscript link, but then only the text opened in my browser. I tried to enter the url in the Utilities page and to download and import the file in the utilities page. Nothing worked. See screenshot.

![script](https://cloud.githubusercontent.com/assets/25794343/24064782/e0773a68-0b66-11e7-8efe-9188cbeeec74.png)

**Comment by uBlock-user** [comment]
He's talking about BETA version, works fine on Chromium.

https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

**Comment by CrescentEclipse** [comment]
Sry, but on firefox this is not a beta version. On chrome this seem to be true.
Maybe I missed something?

**Comment by X01X012013** [comment]
Try to click [here](https://github.com/X01X012013/AdBlockProtector/raw/master/AdBlockProtector.user.js) to install. 
Note: This link is on our home page located at https://x01x012013.github.io/AdBlockProtector/

**Comment by CrescentEclipse** [comment]
Wonderful, it works! :)

**Comment by X01X012013** [comment]
Alright, I'll close this issue now.
