### ISSUE TITLE
kuchniaplus.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#101]
please add to wp.pl domains 

http://www.kuchniaplus.pl/program/program-tv/full/365-obiadow-mariety-mareckiej-2_46463

![capture](https://cloud.githubusercontent.com/assets/15007183/24083778/29e7ccb4-0cb4-11e7-9814-44756b5ddef8.PNG)

**Comment by X01X012013** [comment]
The solution for TVN works for it. Fixed.

**Comment by xxcriticxx** [comment]
@szymon1118 can you please help with this i maybe geolocked

new test link:

http://www.kuchniaplus.pl/w-drodze.html

![capture](https://cloud.githubusercontent.com/assets/15007183/24085401/c2837352-0cd1-11e7-8322-04e92fb8fa96.PNG)

**Comment by X01X012013** [comment]
Hum, it works for me... 
![image](https://cloud.githubusercontent.com/assets/7283682/24085948/3e47edb2-0ccb-11e7-9f28-829d521002a0.png)

**Comment by xxcriticxx** [comment]
maybe my host file i test tomorrow on different pc

**Comment by xxcriticxx** [comment]
yep it works my host file was blocking something extra
