### ISSUE TITLE
parenting.pl, echirurgia.pl

### ISSUE THREAD

**Issue by mirrorsmm** [X01X012013/AdBlockProtector#102]
please add  parenting.pl ,      echirurgia.pl  - blocked movies

**Comment by xxcriticxx** [comment]
@mirrorsmm podaj jaki test linky please

**Comment by mirrorsmm** [comment]
https://parenting.pl/jakie-choroby-moga-wykryc-badania-genetyczne/2

http://www.echirurgia.pl/wyrostek/appendektomia_laparoskopowa.htm

**Comment by xxcriticxx** [comment]
@X01X012013 this part of wp.pl can you see if you can switch player?

**Comment by mirrorsmm** [comment]
no

**Comment by X01X012013** [comment]
Hi, this is fixed in Script 6.107 using solution for `wp.pl`. Please test it out.

**Comment by xxcriticxx** [comment]
yep works thx

**Comment by mirrorsmm** [comment]
to be in operation  ,thank you

**Comment by X01X012013** [comment]
Great, I'll close this issue now.
