### ISSUE TITLE
marinetraffic.com

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#103]
https://forums.lanik.us/viewtopic.php?f=62&t=35695

**Comment by uBlock-user** [comment]
`||marinetraffic.com^$inline-script` works fine, I'm unsure if it breaks anything.

**Comment by X01X012013** [comment]
OK, I'll have a look.

**Comment by uBlock-user** [comment]
This is the anti adblock script - http://cdn.marinetraffic.com/js/mtapp-3.9.10.3ec258.js

**Comment by uBlock-user** [comment]
Any progress ?

**Comment by X01X012013** [comment]
Sorry I was a bit busy these days, I just went to the website, can you tell me what's wrong with it? I don't see any block screen. 
![image](https://cloud.githubusercontent.com/assets/7283682/24249484/13c7ac00-0f99-11e7-84ea-0e0f2bd1619c.png)

**Comment by uBlock-user** [comment]
Quote from the OP himself - **While having AdBlock activated, I can only click on vessels twice to bring up the info card (picture, stats etc.). When clicking on a 3rd vessel it doesn't work and I have to refresh the page to be able to click on more than 2 vessels to bring up the info card.**

**Comment by X01X012013** [comment]
I'll test on Chrome later.

**Comment by uBlock-user** [comment]
Have you tested on chrome yet ?

**Comment by X01X012013** [comment]
It works in Chrome as well. I clicked more than 3 vessels, it responds to the click every time.

**Comment by uBlock-user** [comment]
Working today on Chromim as well, probably a cache issue on my end then. I'm closing this.
