### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#104]
test link for forbes from google search:

https://www.forbes.com/forbes/welcome/?toURL=https://www.forbes.com/sites/davidphelan/2017/03/07/sonos-reveals-great-new-playbase-speaker-hands-on-review/&refURL=https://www.google.com/&referrer=https://www.google.com/

i see something that looks like ad block and wont go away:

![capture1](https://cloud.githubusercontent.com/assets/15007183/24164583/97381454-0e44-11e7-8ef9-9fe02c7d3c11.PNG)

**Comment by uBlock-user** [comment]
Already patched in the by the script. Is the script running ?

**Comment by xxcriticxx** [comment]
yes but i get stuck on the quote of the day cant come pass that

**Comment by xxcriticxx** [comment]
ok works on chrome doesn't work on firefox for me 

can anyone test on firefox please and let me know

**Comment by ghajini** [comment]
works on firefox w / w/o adblock protector
ublock origin
![screenshot 192](https://cloud.githubusercontent.com/assets/20338483/24168016/e2bfb238-0e9e-11e7-8bcd-4c27afca4891.png)

**Comment by uBlock-user** [comment]
If you're running multiple adblockers, remove all, keep only uBO. That could also be the cause.

**Comment by xxcriticxx** [comment]
nope am running only one adblocker

**Comment by X01X012013** [comment]
Hi, it does take a second to skip quote of the day, it is handled by Script.
