### ISSUE TITLE
babblecase.com (related to adf.ly)

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#107]
test link:

http://babblecase.com/2Sv

![capture](https://cloud.githubusercontent.com/assets/15007183/24261967/07da4dfe-0fcf-11e7-98fc-453a9609eeeb.PNG)

**Comment by uBlock-user** [comment]
Yes, this belongs to the adf.ly group. Domain needs to be added.

**Comment by X01X012013** [comment]
Fixed in 6.108.

**Comment by xxcriticxx** [comment]
@X01X012013 anyway to auto update?

**Comment by X01X012013** [comment]
For Tampermonkey, you can click the text in "Last updated" column to manually trigger an update check.

**Comment by xxcriticxx** [comment]
thats what i do all the time but when it updates it tells me there was no script update and the number on the version of your script changes

please add:

http://goto.adflytutor.com

**Comment by xxcriticxx** [comment]
other adfly domains 

j.js
q.gs

**Comment by uBlock-user** [comment]
j.gs and q.gs are already present in the script.

**Comment by xxcriticxx** [comment]
according to this there is few more https://github.com/svn2github/jdownloader/blob/master/src/jd/plugins/decrypter/AdfLy.java#L53

```
private static final String adfDomains   = "adf\\.ly|j\\.gs|q\\.gs|adclicks\\.pw|ay\\.gy";
// belongs to other people who use subdomains and use adf.ly service
private static final String subDomains = "dl\\.nhachot\\.info|chathu\\.apkmania\\.co|alien\\.apkmania\\.co|n\\.shareme\\.in|proxy\\.doujin\\.us|free\\.singlem4a\\.com|adf\\.acb\\.im";
```

**Comment by xxcriticxx** [comment]
adf.ly

    adf.ly
    j.gs
    q.gs
    9.bb
    u.bb

**Comment by xxcriticxx** [comment]
ets you bypass all AdF.ly URLs!

✔ adf.ly
✔ j.gs
✔ q.gs
✔ ay.gy

**Comment by xxcriticxx** [comment]
```
/*adfly*/
// @include       *adf.ly/*
// @include       *j.gs/*
// @include       *q.gs/*
// @include       *9.bb/*
// @include       *u.bb/*
// @include       *adfly.itsrinaldo.net/*
// @include       *chathu.apkmania.co/*
// @include       *go.phpnulledscripts.com/*
```

**Comment by X01X012013** [comment]
Please, summarize it and provide a test link for each domain.

**Comment by xxcriticxx** [comment]
blah you killing me right now

**Comment by X01X012013** [comment]
These are the domains to keep on radar: 
```
goto.adflytutor.com
9.bb - Seems to be inactive
u.bb - Seems to be inactive

adclicks.pw
dl.nhachot.info
chathu.apkmania.co
alien.apkmania.co
n.shareme.in
proxy.doujin.us
free.singlem4a.com
adf.acb.im

adfly.itsrinaldo.net
go.phpnulledscripts.com
```
Since we don't have test links and some of these domains are inactive, I don't think it is a good idea to aggressively apply adfly rule to all these domains without testing. If test links become available, please let me know. I'll close this issue now.
