### ISSUE TITLE
lovesutras.com

### ISSUE THREAD

**Issue by ghajini** [X01X012013/AdBlockProtector#109]
http://www.lovesutras.com/health-and-fitness/story/health-fitness-tips-stay-healthy-fit-young-lifestyle-changes-124012-2016-09-20
antiadblock here....
![screenshot 195](https://cloud.githubusercontent.com/assets/20338483/24312189/71bc82b2-10fd-11e7-9f88-697a22088b24.png)

**Comment by uBlock-user** [comment]
try - `||lovesutras.com/adblocker1.php`

**Comment by uBlock-user** [comment]
Nevermind, already patched in the user-script.

**Comment by uBlock-user** [comment]
I cannot reproduce.

**Comment by uBlock-user** [comment]
uBO Filter - `lovesutras.com##script:inject(abort-on-property-read.js, openPopup)`

**Comment by ghajini** [comment]
hey hii @uBlock-user ... i need to learn ,,whats this
![screenshot 197](https://cloud.githubusercontent.com/assets/20338483/24313055/53d0a5cc-1101-11e7-88bd-40bc200142b2.png)
![screenshot 198](https://cloud.githubusercontent.com/assets/20338483/24313056/53d85ba0-1101-11e7-8ad5-579a5a43c97c.png)
if we can fix it by simple cosmetic filter

also this one 
`if (a.domCmp(["intoday.in", "businesstoday.in"])) {
    a.css("#adbocker_alt { display: none; }");
    a.readOnly("openPopup", function () { });
}`
this fix available in uassets,i think, need to add this doamin too...

**Comment by uBlock-user** [comment]
That uBO filter fixes it just fine if you don't want to use the script.

**Comment by ghajini** [comment]
btw how do i deal with privacy badger in chrome,i get warning adblock

**Comment by uBlock-user** [comment]
Remove it. Privacy Badger is useless if you're using uBO.

**Comment by X01X012013** [comment]
@ghajini You mean that exact line is in uAsset or an equivalent is in uAsset? I don't think that line will work natively... 
The fix in implemented to 6.109, thanks to @uBlock-user .

**Comment by ghajini** [comment]
Thank you
