### ISSUE TITLE
jansatta.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#11]
http://www.jansatta.com/rajya/new-delhi/aisa-leader-booked-for-allegedly-raping-jnu-student/133468/

**Comment by X01X012013** [comment]
Hi, this is fixed in 1.0.71. 

`setReadOnly("RunAds", true);`

**Comment by X01X012013** [comment]
It's been 4 days and there is no reply, I assume the fix worked.
