### ISSUE TITLE
hp.com/pl/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#111]
cookies 

`http://www8.hp.com/pl/pl/home.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/24331297/5a6e27c0-11ff-11e7-8a39-841af5c24395.PNG)

**Comment by uBlock-user** [comment]
is that a cookie notice ?

**Comment by xxcriticxx** [comment]
Yes sorry I posted this in wrong place

**Comment by uBlock-user** [comment]
just kill it with a cometic filter.
