### ISSUE TITLE
gamezhero.com

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#112]
https://github.com/reek/anti-adblock-killer/issues/3008

**Comment by uBlock-user** [comment]
Anything on this one ?

**Comment by X01X012013** [comment]
I'll look into this when I have time.

**Comment by X01X012013** [comment]
The solution for the block screen is added to Script. The 30 seconds countdown needs to be fixed. And the game requires Flash, it works for me.

**Comment by uBlock-user** [comment]
Yes, indeed. except for the countdown everythig is in order, thanks!

**Comment by uBlock-user** [comment]
linking the countdown killer patch here - https://github.com/reek/anti-adblock-killer/issues/3008#issuecomment-289777512

**Comment by X01X012013** [comment]
The fix is added to Script, the countdown now ticks 50 times faster.
