### ISSUE TITLE
breaks mega.nz on Chromium

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#113]
![](https://i.gyazo.com/c87d442f3f33b1478c35c613444fa110.png)

Please check if this happens on Chrome/Opera.

Works fine if I disable the userscripts.

**Comment by X01X012013** [comment]
Can you send the test link?

**Comment by uBlock-user** [comment]
https://mega.nz/#!Lgt0iZ7K!SKiaeRDaOGjZyXtT5pFJDS6pw1e-fOkvRZtu82Fvehc

**Comment by X01X012013** [comment]
It looks like it works on both Opera and Chrome. 
![image](https://cloud.githubusercontent.com/assets/7283682/24417643/76d32b2e-13a6-11e7-91d5-9018ec913d0d.png)
![image](https://cloud.githubusercontent.com/assets/7283682/24417699/a499d530-13a6-11e7-972b-9efa58324013.png)

**Comment by uBlock-user** [comment]
Possibly a ViolentMonkey bug ?

**Comment by X01X012013** [comment]
I don't know, can you test it?

**Comment by uBlock-user** [comment]
Indeed it is. I loaded the same userscript in TM Beta and it works fine here too, but breaks if I use VM, so it's VM bug. I will report it there, thanks for the help
