### ISSUE TITLE
okazje.co

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#114]
we already fixed this in pl list i don't know if you need this for some generic detection

![18f33458-14a1-11e7-88de-7432011b4c71](https://cloud.githubusercontent.com/assets/15007183/24507669/15daf240-152f-11e7-81f8-08e166467c79.PNG)

**Comment by X01X012013** [comment]
Do you know what is the rule they used?

**Comment by uBlock-user** [comment]
add - `okazje.co###AdBlockDetected`

**Comment by X01X012013** [comment]
Awesome. Thanks.

**Comment by X01X012013** [comment]
Looks like everything is good, I'll close this issue.
