### ISSUE TITLE
chicagotribune.com

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#115]
http://www.chicagotribune.com/entertainment/movies/sc-ghost-in-shell-mov-rev-0330-20170330-column.html

![capture](https://cloud.githubusercontent.com/assets/15007183/24519439/29bcb978-1553-11e7-86f5-4ddbd287d675.PNG)

**Comment by uBlock-user** [comment]
cannot reproduce it. Do you have uBO-Extra installed or a script version of it ?

**Comment by xxcriticxx** [comment]
i get this on firefox 52.0.2

**Comment by X01X012013** [comment]
Can you check if this code works? 
```JavaScript
if (a.domCmp(["chicagotribune.com"])) {
    const token = a.win.setInterval(function () {
        if (a.$("#reg-overlay").length) {
            a.$("#reg-overlay").remove()
            a.$("<style> html[data-dss-meterup], [data-dss-meterup] body { o" +
"verflow: scroll !important; } </style>").appendTo("head");
            a.win.clearInterval(token);
        }
    }, 1000);
    a.filter("addEventListener", /^scroll$/);
}
```

**Comment by uBlock-user** [comment]
UBO-Extra is only for Chromium based browsers and not uploaded on AMO, so he doesn't have it.

**Comment by X01X012013** [comment]
@uBlock-user I think the Userscript version will work in FireFox.

**Comment by uBlock-user** [comment]
Sure tell him to give a try.

**Comment by xxcriticxx** [comment]
i got WWIII going on page flashes and blinks all over the place also constantly reloads

**Comment by X01X012013** [comment]
@xxcriticxx Can you try to paste this code at the end of AdBlock Protector Script and see if this works? 
https://github.com/X01X012013/AdBlockProtector/issues/115#issuecomment-290565665

**Comment by xxcriticxx** [comment]
what is good tool to capture screen i try 3 different once nothing wants to record.

**Comment by X01X012013** [comment]
@xxcriticxx You mean record screen into a video? Try Open Broadcaster Software.

**Comment by xxcriticxx** [comment]
in to gif or something i jsut want to show you what happen and you right script is fast after while that white list msg comes up

**Comment by xxcriticxx** [comment]
check this out

http://imgur.com/a/kIIea

**Comment by uBlock-user** [comment]
How did that happen ?

**Comment by xxcriticxx** [comment]
@uBlock-user that happens to the page with ubo extra running 

@X01X012013 if i add your code i get only white page nothing on it 

![capture](https://cloud.githubusercontent.com/assets/15007183/24558030/ca0dd678-1607-11e7-99a6-96786b74413a.PNG)

**Comment by uBlock-user** [comment]
uBO-Extra extension or the script ?

**Comment by xxcriticxx** [comment]
@uBlock-user ubo extra script that you gave me

**Comment by X01X012013** [comment]
Thanks for the feedback, I'll have a look.

**Comment by xxcriticxx** [comment]
@X01X012013 your code works after i clear history and cookies 

@uBlock-user with ad protector off and ubo extra on i get white page

**Comment by xxcriticxx** [comment]
now after few more times clearing my histroy all works with regular ad protector what the f---

**Comment by uBlock-user** [comment]
@xxcriticxx Alright, I tested on Firefox Portable 52.0.2 stable release.

- I cannot reproduce any anti adblock notice, meaning it's a filter list issue.

- Secondly, IL crap only works on Chromium and not Firefox, so uBO-Extra is NOT needed and rather causes a white page to be loaded, so remove the script I gave you and only use AdBlock Protector Script in TM.

**Comment by X01X012013** [comment]
I can reproduce the block screen. The rule I posted before kind of work, but blocking `scroll` event breaks lazy loading that the page uses.

**Comment by xxcriticxx** [comment]
@X01X012013 clear your history couple time and it all work again. i had problem with pictures they where black but after 4 or 5 times i clear the browser all works.

**Comment by uBlock-user** [comment]
Is the block screen gone @xxcriticxx ? Or are you still seeing the block screen ?

**Comment by xxcriticxx** [comment]
screen is gone i am all good with reg ver of ad block protector and modify ver of ad block protector

would browsers share cookies or browsing history? answer should be no right?

**Comment by X01X012013** [comment]
Different browsers should not share any data between them without asking.

**Comment by xxcriticxx** [comment]
i think you can mark this as fixed

**Comment by X01X012013** [comment]
Yep, the website magically works now...
