### ISSUE TITLE
business-standard.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#12]
http://www.business-standard.com/article/economy-policy/ndtv-petitions-national-green-tribunal-against-sagarmala-project-116083100762_1.html

**Comment by ashutoshgoyal** [comment]
Kindly help Sir.

**Comment by X01X012013** [comment]
I was quite busy recently, I will look into this now.

**Comment by X01X012013** [comment]
This is fixed in 1.0.72, sorry about the delay.

**Comment by ashutoshgoyal** [comment]
Working fine. many thanks :)
