### ISSUE TITLE
dbzsuper.tv

### ISSUE THREAD

**Issue by mattdx123** [X01X012013/AdBlockProtector#120]
I get pop ups every time I press on a video

Text link: https://www2.dbzsuper.tv/

**Comment by X01X012013** [comment]
OK, I'll have a look.

**Comment by uBlock-user** [comment]
I don't get any popups by default, neither can I find any popup inducing third-party domains.

**Comment by X01X012013** [comment]
I found the problem. 
`||cloudfront.net$script,domain=www2.dbzsuper.tv`

**Comment by uBlock-user** [comment]
`cloudfront.net` is already blocked by Easylist there on the domain, he probably didn't force update the filters.

**Comment by X01X012013** [comment]
I couldn't locate it. Can you tell me which rule in EasyList does that?

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/6ea570c88a274bb0bd255f0f5c626644.png)

**Comment by uBlock-user** [comment]
Just run the logger and put `cloudfront.net` in the filter search.

**Comment by X01X012013** [comment]
That rule does not match the script requested by `dbzsuper.tv`.

**Comment by uBlock-user** [comment]
just add `||cloudfront.net$script,domain=dbzsuper.tv` that will do the job. @mattdx123 provide feedback please.

**Comment by X01X012013** [comment]
@uBlock-user That's exactly what I did.

**Comment by X01X012013** [comment]
I just tested again, everything is working. I'll close this issue now.
