### ISSUE TITLE
tech.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#122]
adblock is back can someone please test 

few test links:

http://tech.wp.pl/samoloty-z-napedem-atomowym-niebezpieczne-monstra-6105160630968961a
http://tech.wp.pl/to-nie-bedzie-dobry-weekend-dla-klientow-polskich-bankow-duze-utrudnienia-6104508434662529a
http://tech.wp.pl/dla-nich-bankomaty-to-magia-uciekinierzy-z-korei-polnocnej-musza-uczyc-sie-zyc-w-nowym-swiecie-6106661250078849a

**Comment by X01X012013** [comment]
Fixed.

**Comment by xxcriticxx** [comment]
tested works thx
