### ISSUE TITLE
gamereactor.*

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#124]
Test-case - http://www.gamereactor.eu/

Anti adblock + cookie based ad solution

```javascript
if (a.domCmp(["gamereactor.eu"])) {
    a.readOnly("detectAdblockUser", function ( ) { });
    a.cookie("countdownToAd", "-1");
}
```

List of domains - 

```
gamereactor.dk gamereactor.se gamereactor.no gamereactor.fi gamereactor.de 
 gamereactor.it gamereactor.es gamereactor.pt gamereactor.fr gamereactor.nl
```

**Comment by uBlock-user** [comment]
@X01X012013 All domains using the anti adblock script, so the same solution applies on the rest fyi

**Comment by xxcriticxx** [comment]
i can't reproduce

**Comment by X01X012013** [comment]
To match `*.example.*` you can use `a.domInc(["example"])`. 

On line 3074 of their HTML: `if (typeof powerpuff == 'undefined') // should have been defined in multi.php, which is blocked by adblock`
Actually, it looks like `multi.php` is not blocked.

**Comment by uBlock-user** [comment]
Ah yes because of this filter in Easylist - `@@||gamereactor.net/advertisement.js`

**Comment by X01X012013** [comment]
Wait a second, this is a problem, `multi.php` serves actual ads...

**Comment by uBlock-user** [comment]
Could you atleast add this - `a.cookie("countdownToAd", "-1");`

After brosing dew articles I get a page which replaces the article like this - https://i.gyazo.com/88bab6a5f6fd8af53804bba721ef911b.png

**Comment by X01X012013** [comment]
Yea, I'll also add this rule to override EasyList's white-listing, it is letting ads through. 
`||openx.gamereactor.dk/multi.php$script,domain=www.gamereactor.eu,important`

**Comment by X01X012013** [comment]
Code never lies, comments sometimes do. This is fixed, white-list overridden with `$important`.

**Comment by uBlock-user** [comment]
Thanks.

**Comment by X01X012013** [comment]
This is exactly why we need a robot to watch EasyList... and not trust comments...

**Comment by uBlock-user** [comment]
uBO has introduced `$badfilter` in 1.11.5, which can be used to tell uBO not to load such filters.

**Comment by X01X012013** [comment]
Do you have a link to the documentation? 
Also, we would still need a robot to watch EasyList, since we are not going to undo their work with human effort. 
I plan on making a bot to extract white-listings, and send a request, if the response is longer than 100 characters, the bot will flags it for review.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/192#issuecomment-285904675

**Comment by X01X012013** [comment]
So with the new syntax, the filter would be `@@||openx.gamereactor.dk/multi.php?$script,badfilter`? 

Not a GitHub bot, probably a Selenium based bot.

**Comment by uBlock-user** [comment]
Yes, probably. Consult with gorhill if it doesn't work, I haven't tested anything on that front.

**Comment by uBlock-user** [comment]
> I plan on making a robot to extract white-listings, then send requests to white-listed servers, if the response is longer than 100 characters, the bot will flag it for review.

How does that stop from Easylist filters form being applied ?

**Comment by X01X012013** [comment]
It doesn't, but it will let us know which filter is potentially bad.

**Comment by X01X012013** [comment]
`$badfilter` is totally not working, rolling back to `$important`.

**Comment by uBlock-user** [comment]
`$badfilter` will only work on the dev version of uBO, did you test it on the dev version ?

**Comment by X01X012013** [comment]
Eh... No... We'll use `$important` for this time, we'll try `$badfilter` next time.

**Comment by uBlock-user** [comment]
uBO 1.12.0 has been released to the web store. You can try `$badfilter` from now on.

**Comment by X01X012013** [comment]
Awesome, we'll try it next time.
