### ISSUE TITLE
animmex.*

### ISSUE THREAD

**Issue by mattdx123** [X01X012013/AdBlockProtector#125]
I get pop ups and when I try to watch a video I get a text message saying to disable my adblock and script blockers

**Comment by uBlock-user** [comment]
Do you have uBlock Origin installed first ? If not, do it and remove any other adblocker.

Afterwords, add these filters for anti adblock and popup


```
animmex.*##script:inject(bab-defuser.js)
@@||4553t5pugtt1qslvsnmpc0tpfz5fo.xyz^$inline-script
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(bab-defuser.js)
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(abort-on-property-read.js, _gunggo)
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz###babasbmsgx
animmex.*###M148617ScriptRootC75329
```

**Comment by X01X012013** [comment]
OK, I'll have a look. I think `bab-defuser.js`'s functionalities should be already in Script.

**Comment by uBlock-user** [comment]
Those filters remove all crap off the animmex domains and clean them up real nice.

**Comment by uBlock-user** [comment]
list of domains - https://github.com/uBlockOrigin/uAssets/issues/144#issuecomment-247823977 

Could be more as those were accumulated by me back in Sept 2016.

**Comment by mattdx123** [comment]
Thanks!!!

**Comment by X01X012013** [comment]
After some testing, these 4 rules would do the job. 
```
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(abort-on-property-read.js, _gunggo)
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz###babasbmsgx
animmex.*###M148617ScriptRootC75329
animmex.*##a[href^="https://forum.animmex.com/viewtopic.php"]
```

**Comment by uBlock-user** [comment]
Need to whitelist inline-script of that domain or the player won't intialise.
`@@||4553t5pugtt1qslvsnmpc0tpfz5fo.xyz^$inline-script` because of badfilter present in uBlock Filters - `||4553t5pugtt1qslvsnmpc0tpfz5fo.xyz$inline-script`

**Comment by uBlock-user** [comment]
and you also need to add bab-defuser for that temp domain - `4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(bab-defuser.js)` They have two Anti Adblock scripts present.

**Comment by X01X012013** [comment]
It works fine when I tested it...

**Comment by X01X012013** [comment]
I don't think `||4553t5pugtt1qslvsnmpc0tpfz5fo.xyz$inline-script` is wrong, it does the job of killing BlockAdBlock.

**Comment by uBlock-user** [comment]
On my end it doesn't the player never loads because of that filter. Also BlockAdblock is always killed by `bab-defuser` not by blocking the inline-script on uBO.

**Comment by X01X012013** [comment]
Can you provide a test link? It works for me... 
https://www.animmex.tv/video/23428/the-night-of-s01e08-the-call-of-the-wild
![image](https://cloud.githubusercontent.com/assets/7283682/24658538/3a88a1b0-1907-11e7-9b05-ec4155155353.png)

**Comment by X01X012013** [comment]
Instead, using all your rules will breaks comment section and video size: 
![image](https://cloud.githubusercontent.com/assets/7283682/24658886/4fc9c2b0-1908-11e7-9013-61586b96cf9a.png)

**Comment by uBlock-user** [comment]
It appears to be working here as well, I was having issues few weeks ago so had to whitelist the inline-script for that temp domain, now it loads even though the inline-script remains blocked, that's strange. 

Ofcourse you will have to whitelist `disqus.com` and it's CDN if you're using `||$third-party,script,domain=animmex.tv`. My reason for blocking all third-party scripts is they're connecting to random domains for inducing third-party popups namely from `n206adserv.com` , `npikrbynhuzi.com
`, `wmvcxgpdgdkz.com`.

**Comment by uBlock-user** [comment]
They can add more and more as the webmaster of the `animmex` group is the most desperate guy I have ever met, you can see from the Easylist whitelist he's running 4-5 third-party scripts for checking anti adblock detection on top of those 2 anti adblock scripts just to troll the users.

**Comment by uBlock-user** [comment]
The video size issue never happens on my end, so I don't know what's up with that. Probably a fuck up on the website's end.

**Comment by uBlock-user** [comment]
Also whitelisting those third-party domains comes with a side-effect they induces popups from rotating ad-servers.

**Comment by X01X012013** [comment]
Yea... I haven't got any popup yet, but some of the 3rd party scripts will break video size if blocked.

**Comment by uBlock-user** [comment]
@mattdx123 provide feedback please, the issue has been already fixed.

**Comment by X01X012013** [comment]
The website is still fully functional for me, I'll remove `Test In Progress` tag.

**Comment by uBlock-user** [comment]
FYI `4553t5pugtt1qslvsnmpc0tpfz5fo.xyz` is not longer the domain used and has been replaced with `finalservers.net`

**Comment by ghajini** [comment]
user reported problems here `https://github.com/gorhill/uBlock/issues/2520`

**Comment by uBlock-user** [comment]
@X01X012013 Turns out, that `inline-script` was stopping the video from playing and since the anti adblock script is ran first, there's a race condition developing on `finalservers.net` domain. Can you do something about this race condition which executes before the `bab-defuser.js` scriptlet ?

Test-case - https://amx-assets-1.finalservers.net/KL8jJhGjUN0g3HuGhUHSa5XRZ9MVrjXUuvkbCmFyo1GBMFPhvcFyc7gGKdoBxSV/N3WPL4Y3RIcyKUcBunsEyFZal6Imwlrkgcf6E2ZSZG0M8Avvtc.php?id=40920

**Comment by X01X012013** [comment]
As far as I tested, `$inline-script` works fine. If there is a video that does not work, please provide the link from `animmex.*`.

**Comment by X01X012013** [comment]
This is our current solution: 
```
||finalservers.net^$inline-script
finalservers.net###babasbmsgx
finalservers.net##script:inject(abort-on-property-read.js, _gunggo)
animmex.*###M148617ScriptRootC75329
animmex.*##a[href^="https://forum.animmex.com/viewtopic.php"]
```

**Comment by uBlock-user** [comment]
Yes, I'm using those filters too and the video doesn't play for me. Gorhill mentioned that too.

Link - https://www.animmex.tv/video/40920/prison-break-s05e01-ogygia

**Comment by uBlock-user** [comment]
It remains in the buffering state and nothing happens any further. 

![](https://i.gyazo.com/b7a3129b6b4248f44ca08b8aae608b4e.png)

Does that happen to you ?

**Comment by X01X012013** [comment]
Does the video works with ad blocker disabled?

**Comment by X01X012013** [comment]
OK, I added a few lines to Script, the player should now behave properly, the video still doesn't work though, it doesn't work with uBO disabled.

**Comment by uBlock-user** [comment]
I'm not gonna disable uBO to test that. That website is filled with third-party adware and what not. You will have to test that on your own.

Those few lines just break the video from buffering.

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/d051f7795063beb05bc9dab98ee49046.png)

That's the reason the video doesn't play atleast on my end.

**Comment by X01X012013** [comment]
The solution is fully working, it's their media server that is broken.

**Comment by uBlock-user** [comment]
But you still need to remove the code you added that breaks the buffering.

**Comment by X01X012013** [comment]
@uBlock-user How does that break buffering? With that snippet, the player behave exactly the same as when uBO is disabled.

**Comment by uBlock-user** [comment]
@X01X012013 If that's how it is, then we should close the case on this one.

**Comment by X01X012013** [comment]
If the request is blocked by firewall, you'll get connection timeout. 

The server did send a response: 
```
HTTP/1.1 403 Forbidden
Content-Type: text/html
Content-Length: 345
Date: Sat, 08 Apr 2017 20:12:16 GMT
Server: lighttpd/1.4.35
```
Chances are their lighty server is misconfigured.

**Comment by uBlock-user** [comment]
403 Forbidden appears when your request is denied or blocked , also the connection is being refused by the server so it is screwed up at their end.

**Comment by X01X012013** [comment]
Chromium will print `ERR_CONNECTION_REFUSED` to console when a HTTP403 response is received. It's kind of misleading, since it's not really the "connection" that is refused, it's "request" or "access". 

These are all the possible HTTP status codes: 
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by uBlock-user** [comment]
> Chromium will print ERR_CONNECTION_REFUSED to console

It just doesn't print at the console, it also sends that error if you try to download the video via the .mp4 link, for example, click on this - https://amx.cdn-r2b.finalservers.online/video/a9761f186685975e52dbeb5bfd22061a/58e94a98/iphone/40920.mp4 Either a succesful download should begin or you will see what I see in the image below

![](https://i.gyazo.com/867605876295cc92696b6b8aee49a3c8.png)

**Comment by X01X012013** [comment]
Eh... I'm not seeing that... 
![image](https://cloud.githubusercontent.com/assets/7283682/24832281/bf894ae4-1c69-11e7-9fae-ce842a3debdd.png)

**Comment by X01X012013** [comment]
Hum... Chrome behaves differently... But you shouldn't see the "can't be reached" page when the server returns HTTP403... 
![image](https://cloud.githubusercontent.com/assets/7283682/24832289/047f5cb0-1c6a-11e7-8250-e272fbc34f93.png)

**Comment by uBlock-user** [comment]
That's on Opera, try Chrome.

**Comment by X01X012013** [comment]
The second image is Chrome 57.

**Comment by uBlock-user** [comment]
In your case its 403 Forbidden, but atleast it opens the page and loads the player, mine simply throws that error. This is why I believe it's refusing connections from my ISP's IP range.

**Comment by X01X012013** [comment]
That would be quite dumb, I don't see the benefit of blocking the full IP range of an ISP. That would remove a good chunk of audience for no reason. 
Do you mind telling me which ISP you are with?

**Comment by uBlock-user** [comment]
Sorry, I'm not comfortable revealing that.

**Comment by X01X012013** [comment]
Ah, I can understand that. You can try to ask your ISP to re-roll your IP and see if it's the IP that is assigned to you that is bad.

**Comment by uBlock-user** [comment]
My IP changes whenever I reboot my router within the range and it still happens. I also tried TouchVPN chrome extension where I can pick my IP from 8-10 countries, so I tried US, no change. So I believe the fuck up is at the media server's end.
