### ISSUE TITLE
titulky.com

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#128]
cookie based anti adb overlay, remove all cookies if you cannot reproduce.

add 

```javascript
if (a.domCmp(["titulky.com"])) {
    a.readOnly("adbfetected", function () { });
}
```

**Comment by X01X012013** [comment]
Looks like FuckAdBlock. 
https://www.titulky.com/js/fadb.js
This should work too: `a.generic.FuckAdBlock("FADB", "fADB");`

**Comment by uBlock-user** [comment]
Sure, if there's already a generic solution.

**Comment by uBlock-user** [comment]
Setting the cookie would do the job too - `a.cookie("adbwshown", true);`

**Comment by X01X012013** [comment]
The fix is added to Script. Thanks for your contribution.
