### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#13]
http://timesofindia.indiatimes.com/india/Senior-Supreme-Court-judge-rips-into-CJI-headed-collegium-shuns-selection-meetings-calls-them-opaque/articleshow/53987683.cms

**Comment by X01X012013** [comment]
This is patched into 1.0.73. 

`setReadOnly("_0x8cae", "");`

**Comment by X01X012013** [comment]
This website broke again and was fixed in issue #16

**Comment by X01X012013** [comment]
Please open a new issue if this website breaks again.
