### ISSUE TITLE
pudelekx.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#131]
test link:

http://pudelekx.pl/zrzucil-80-kilo-w-rok-to-jak-dostac-druga-szanse-64158

![capture](https://cloud.githubusercontent.com/assets/15007183/24636989/fa4a2d9a-18ab-11e7-9584-b6c984399f7b.PNG)

**Comment by X01X012013** [comment]
OK, that looks like... `wp.pl` player?

**Comment by xxcriticxx** [comment]
that's correct

**Comment by uBlock-user** [comment]
try - `pudelekx.pl##.windowErrCont`

**Comment by X01X012013** [comment]
Doesn't work, it removed the block screen but the player still refuse to play. Need to replace the player.

**Comment by uBlock-user** [comment]
Thought so.

**Comment by X01X012013** [comment]
We have the code to replace the player, I just need to test it to make sure it works on this domain...

**Comment by X01X012013** [comment]
Notes for devs: 
rule.js line 443

**Comment by X01X012013** [comment]
Actually we didn't need to replace the player, used the other solution from Adguard, it's fixed now.
