### ISSUE TITLE
newsquest.co.uk and related domains

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#137]
link - http://www.dailyecho.co.uk/news/15074556.UPDATE_AND_PHOTOS__Motorway_blocked_after_crash_involving_lorry__van_and_car/

List of domains(100+) - http://www.newsquest.co.uk/our-titles/

solution - `a.noAccess("_sp_");`

**Comment by X01X012013** [comment]
Hum... it would not be safe to make it generic... I'll use a script to collect all the domains...

**Comment by uBlock-user** [comment]
testing 100+ domains, collecting them and adding them is a pain, otherwise I would have done it already.

**Comment by uBlock-user** [comment]
You can do a crude search here - https://publicwww.com/

**Comment by X01X012013** [comment]
["sthelensstar.co.uk","runcornandwidnesworld.co.uk","leighjournal.co.uk","warringtonguardian.co.uk","northwichguardian.co.uk","middlewichguardian.co.uk","knutsfordguardian.co.uk","wilmslowguardian.co.uk","creweguardian.co.uk","thewestmorlandgazette.co.uk","newsquest.co.uk","messengernewspapers.co.uk","lancashiretelegraph.co.uk","asianimage.co.uk","chorleycitizen.co.uk","theboltonnews.co.uk","burytimes.co.uk","prestwichandwhitefieldguide.co.uk","wirralglobe.co.uk","autoexchange.co.uk","chesterlestreetadvertiser.co.uk","consettstanleyadvertiser.co.uk","darlingtonaycliffesedgefieldadvertiser.co.uk","darlingtonandstocktontimes.co.uk","durhamadvertiser.co.uk","edition.pagesuite-professional.co.uk","durhamtimes.co.uk","northyorkshireadvertiser.co.uk","thenorthernecho.co.uk","northernfarmer.co.uk","wearvalleyadvertiser.co.uk","gazetteherald.co.uk","yorkpress.co.uk","cravenherald.co.uk","ilkleygazette.co.uk","keighleynews.co.uk","thetelegraphandargus.co.uk","wharfedaleobserver.co.uk","herefordtimes.com","ludlowadvertiser.co.uk","redditchadvertiser.co.uk","bromsgroveadvertiser.co.uk","droitwichadvertiser.co.uk","cotswoldjournal.co.uk","eveshamjournal.co.uk","tewkesburyadmag.co.uk","dudleynews.co.uk","halesowennews.co.uk","stourbridgenews.co.uk","kidderminstershuttle.co.uk","ledburyreporter.co.uk","malverngazette.co.uk","worcesternews.co.uk","southendstandard.co.uk","essexcountystandard.co.uk","gazette-news.co.uk","clactonandfrintongazette.co.uk","harwichandmanningtreestandard.co.uk","braintreeandwithamtimes.co.uk","halsteadgazette.co.uk","guardian-series.co.uk","brentwoodweeklynews.co.uk","chelmsfordweeklynews.co.uk","maldonandburnhamstandard.co.uk","thurrockgazette.co.uk","basildonrecorder.co.uk","echo-news.co.uk","bucksfreepress.co.uk","theargus.co.uk","redhillandreigatelife.co.uk","romseyadvertiser.co.uk","dailyecho.co.uk","hampshirechronicle.co.uk","basingstokegazette.co.uk","andoveradvertiser.co.uk","stalbansreview.co.uk","watfordobserver.co.uk","heraldseries.co.uk","banburycake.co.uk","bicesteradvertiser.net","oxfordmail.co.uk","oxfordtimes.co.uk","witneygazette.co.uk","falmouthpacket.co.uk","smallholder.co.uk","southwestfarmer.co.uk","dorsetecho.co.uk","bournmouthecho.co.uk","bridportnews.co.uk","wiltsglosstandard.co.uk","gazetteseries.co.uk","bridgwatermercury.co.uk","burnhamandhighbridgeweeklynews.co.uk","chardandilminsternews.co.uk","middevonstar.co.uk","somersetcountygazette.co.uk","thisisthewestcountry.co.uk","yeovilexpress.co.uk","wiltshiretimes.co.uk","swindonadvertiser.co.uk","salisburyjournal.co.uk","boxingnewsonline.net","engagedinvestor.co.uk","globalreinsurance.com","insurancetimes.co.uk","pensions-insight.co.uk","strategic-risk-global.com","reward-guide.co.uk","thestrad.com","times-series.co.uk","borehamwoodtimes.co.uk","ealingtimes.co.uk","enfieldindependent.co.uk","haringeyindependent.co.uk","harrowtimes.co.uk","hillingdontimes.co.uk","newsshopper.co.uk","croydonguardian.co.uk","epsomguardian.co.uk","streathamguardian.co.uk","suttonguardian.co.uk","wandsworthguardian.co.uk","wimbledonguardian.co.uk","surreycomet.co.uk","kingstonguardian.co.uk","richmondandtwickenhamtimes.co.uk","campaignseries.co.uk","southwalesguardian.co.uk","milfordmercury.co.uk","pembrokeshirecountyliving.co.uk","westerntelegraph.co.uk","tivysideadvertiser.co.uk","southwalesargus.co.uk","cotswoldessence.co.uk","freepressseries.co.uk","monmouthshirecountylife.co.uk","barryanddistrictnews.co.uk","penarthtimes.co.uk","eveningtimes.co.uk","s1cars.com","s1community.com","s1homes.com","s1jobs.com","s1rental.com","thescottishfarmer.co.uk","heraldscotland.com","thenational.scot"]

**Comment by X01X012013** [comment]
Looks good? 
Script used to collect them: 
```JavaScript
// ==UserScript==
// @name NewsQuest Scraper
// @description Collect domains of NewsQuest
// @author X01X012013
// @version 1
// @encoding utf-8
// @match http://www.newsquest.co.uk/our-titles/
// @grant none
// @run-at document-idle
// ==/UserScript==

(function() {
    "use strict";

    //Domains that are found
    let domains = [];
    //Get "section" elements array
    const sections = document.querySelectorAll("section");
    //Loop through each "section" and find "a" elements
    for (let i = 0; i < sections.length; i++) {
        const as = sections[i].querySelectorAll("a");
        //Loop through each "a" elements and get domain
        for (let j = 0; j < as.length; j++) {
            const href = as[j].href;
            //Skip if the protocol is "tel://"
            if (href.startsWith("tel://")) {
                continue;
            }
            //All other domains starts with "http://"
            //This algorithm is safe for this specific case
            let domain = href.split("/")[2].toLowerCase();
            if (domain.startsWith("www.")) {
                domain = domain.substr(4);
            }
            //Check for duplicate and add to domains array
            if (!domains.includes(domain)) {
                domains.push(domain);
            }
        }
    }
    //All done, print array to console
    console.log(domains);
    console.log(JSON.stringify(domains));

})();
```

**Comment by uBlock-user** [comment]
Yep that is all.

**Comment by X01X012013** [comment]
Added to Script.

**Comment by uBlock-user** [comment]
Were all domains reproducible ?

**Comment by X01X012013** [comment]
@uBlock-user I don't know, I'm not going to test all of them.

**Comment by uBlock-user** [comment]
Thought so. I'm closing this then.

**Comment by X01X012013** [comment]
I'll see if I can make a robot to test them for me.
