### ISSUE TITLE
Auto update code for uBO-Extra.user.js

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#138]
As per your suggestion here - https://github.com/X01X012013/AdBlockProtector/issues/95#issuecomment-292169575

```javascript
// ==UserScript==
// @name         uBO-Extra
// @version      2.19
// @description  A companion user-script to uBlock Origin which helps to gain ability to foil early anti-user mechanisms working around content blockers or even a browser privacy settings.
// @icon         https://raw.githubusercontent.com/gorhill/uBO-Extra/master/icon128.png
// @author       Raymond Hill
// @include      http://*/*
// @include      https://*/*
// @grant        none
// @run-at       document-start
// @connect      *
// @require      https://raw.githubusercontent.com/gorhill/uBO-Extra/master/contentscript.js
// @homepage     https://github.com/gorhill/uBO-Extra/
// @supportURL   https://github.com/gorhill/uBO-Extra/issues
// ==/UserScript==
```

**Comment by X01X012013** [comment]
OK, this may or may not work. TM will not add scripts that are loaded on the fly to Content Security Policy so it will sometimes fail to run. Please try it out and see how well it works. It will not take effect the first time you browse to a page since it wouldn't have the script cached. It will check for update once a day. 
https://gist.github.com/X01X012013/64110dfac36b0ec4c3cd0af169eb23c3

**Comment by X01X012013** [comment]
OK, I think I know the problem... Content Security Policy allows a web page to block all in-line tags, which would break `unsafeWindow.eval`, I think the native uBO-Extra plug-in would not work on those pages neither...

**Comment by uBlock-user** [comment]
Thanks, this is what I received in the console - `uBO-Extra Loader updated cached script.`

**Comment by uBlock-user** [comment]
Alright on subsequent visits to Github, console outputs this errors - https://i.gyazo.com/2b186a14630054ef623c4115be6e03d2.png

**Comment by uBlock-user** [comment]
Still I'm not really sure if it updated it or not. Won't changing the version from `2.19` to `2.20` force the file to be downloaded fresh or do I really need this?

**Comment by X01X012013** [comment]
Yes, changing the version will re-download all `@require`d scripts. You obviously don't really need my loader if you wish to trigger updates manually by changing the version number of your Userscript. Keep in mind that the downloaded file will be the one found on the server at the time of download, not the one with matching version number. 

The loader will update cached script once per day, so you will only see the console message once per day. In version 1.1, I added a button to TM menu that let you check for update manually. 

Do you get the same error using your Userscript? I don't think it's an issue with the loader.

**Comment by uBlock-user** [comment]
Thanks for all your help and efforts, but I have decided to use mine. Also I use VM rather than TM, so I won't be seeing any update check button in the dashboard fyi.

> Do you get the same error using your Userscript? I don't think it's an issue with the loader.

Don't worry about the error, Github has it's own strict CSP policy and won't allow any inline unsafe executions on its domain. FYI - https://githubengineering.com/githubs-csp-journey/

**Comment by X01X012013** [comment]
Ah, that's fine. Closing this issue then.

**Comment by uBlock-user** [comment]
just an FYI, if we use `example.com##script:inject(noeval.js)` filter then that will not allow this script to run on `example.com` domain.

**Comment by jspenguin2017** [comment]
BTW this is the new link: https://gist.github.com/jspenguin2017/64110dfac36b0ec4c3cd0af169eb23c3

@uBlock-user Hum... Yea, if uBO is faster then that would happen.

**Comment by uBlock-user** [comment]
> You can change unsafeWindow.eval to injecting a script tag instead.

I will need you to demonstrate me or do it yourself.

**Comment by jspenguin2017** [comment]
The gist is updated, have a look 😄

**Comment by uBlock-user** [comment]
Thanks, works fine as expected.
