### ISSUE TITLE
drfile.net

### ISSUE THREAD

**Issue by darkmorpher** [X01X012013/AdBlockProtector#139]
Site: Drfile.net
Blocking script - _BlockAdblock_

**Comment by X01X012013** [comment]
I don't see any block screen, and I couldn't find BAB code in the page source. Can you provide a test link? The home page works fine.

**Comment by darkmorpher** [comment]
http://drfile.net/dtkd3wgg0ugo

Wait 5-10 sec

**Comment by uBlock-user** [comment]
Cannot reproduce it, the BAB script is present at the end of the page.

**Comment by X01X012013** [comment]
I think it's fixed by some rule in uBO filters, I see BAB code in the source, but no block screen. Waited over a minute and scrolled up and down.

**Comment by uBlock-user** [comment]
anyways adding `drfile.net##script:inject(bab-defuser.js)` will fix it at our end.

**Comment by darkmorpher** [comment]
> I think it's fixed by some rule in uBO filters
Yeah.

**Comment by X01X012013** [comment]
https://uplod.ws/ home page is working fine for me, if you are experiencing issues with it, please post a test link and a short explanation.

**Comment by uBlock-user** [comment]
@darkmorpher Same BAB script, I cannot reproduce it, for the sake of argument, add the domain name with a comma to `drfile.net` filter I posted and that will do the job.
