### ISSUE TITLE
financialexpress.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#14]
http://www.financialexpress.com/industry/tech/ahead-of-reliance-jio-storm-vodafone-idea-cellular-others-slip-in-qtr-bharti-airtel-holds-fort/367066/

**Comment by X01X012013** [comment]
This is fixed in 1.0.74. 

`setReadOnly("RunAds", true);`

**Comment by ashutoshgoyal** [comment]
works fine. Thanks,
