### ISSUE TITLE
gadgetstouse.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#15]
http://gadgetstouse.com/featured/all-about-jio-apps-bouquet/49925

**Comment by X01X012013** [comment]
Hi there, this website works fine for me, can you provide a screenshot of the block screen that you are seeing? 

![screenshot](http://i.imgur.com/bJNMJiY.png)

**Comment by ashutoshgoyal** [comment]
![image](https://cloud.githubusercontent.com/assets/20591484/18340225/6d8d9014-75c1-11e6-98be-4b390cc14cd6.png)

**Comment by X01X012013** [comment]
Hi, I see that Anti-AdblockKiller logs that `Antiblock3{dom}` is detected, can you try to update your AAK script?

**Comment by ashutoshgoyal** [comment]
I use your ABP script 1.1.1 in tapermonkey 4.1.10 . Both updated to latest version. Still problem persists.
