### ISSUE TITLE
usapoliticstoday.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#19]
http://www.usapoliticstoday.com/
adblock warning showing on scroll

**Comment by X01X012013** [comment]
Sorry I was super busy these days. This is fixed into 1.1.4. 

`activateEvalFilter();`

**Comment by X01X012013** [comment]
Sorry I was super busy these days. This is fixed into 1.1.4. 

`activateEvalFilter();`

**Comment by ashutoshgoyal** [comment]
working fine. Thanks.
