### ISSUE TITLE
portal.abczdrowie.pl adblock detection

### ISSUE THREAD

**Issue by Eva850** [X01X012013/AdBlockProtector#2]
https://portal.abczdrowie.pl/jak-wyjmowac-kleszcza
Screenshot: https://drive.google.com/open?id=0B6g6Av7dwyPFQ0Nybml1OXpHMUE
Adguard
EasyList
Adblock Polish Rules
Anti Adblock Killer
Adblock Warning Removal List
Greasemonkey + Anti Adblock Killer + Adblock Protector

**Comment by X01X012013** [comment]
Hi there, this website's video will not load even with AdBlocker disabled. 
![screenshot](http://i.imgur.com/W80V8CN.png)

**Comment by Eva850** [comment]
Hi, This video loads fine for me when I use browser without any add-ons.
Screenshot: https://drive.google.com/file/d/0B6g6Av7dwyPFZE5zMzZDc0hsRms/view

**Comment by X01X012013** [comment]
@Eva850 
The website is working now. Add the following: 
`@@adv.wp.pl/RM/Box/empty.gif`
To your AdBlocker. Anti-Adblock Killer will take care of the rest. When Tampermonkey ask you, click allow.

**Comment by Eva850** [comment]
It works for me. Thank you very much!
