### ISSUE TITLE
rajasthanpatrika.patrika.com

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#20]
http://rajasthanpatrika.patrika.com/story/business/ow-aadhar-card-will-be-linked-to-rail-reservation-2327744.html

**Comment by X01X012013** [comment]
Hi, I am not getting any block screen. Can you show me a screenshot? 

![screenshot](http://i.imgur.com/hKCVOTt.png)

**Comment by ashutoshgoyal** [comment]
![image](https://cloud.githubusercontent.com/assets/20591484/18460078/35b5e4ba-798c-11e6-9e30-1802328b3f58.png)

**Comment by X01X012013** [comment]
Hi, I cannot reproduce this issue. Can you tell me your setup? This will include your browser, adblocker, script host, and subscribed list and scripts.

**Comment by ashutoshgoyal** [comment]
Chrome 54.0.2840.16 beta-m (64-bit)

uBlock origin 1.9.4 
In 3rd party filters -> ads -> Checked 
" Adblock Warning Removal List", 
"Anti-Adblock Killer | Reek‎"
"Easy List"

TaperMonkey 4.1.10
Script AdBlock Protector 1.1.4

**Comment by X01X012013** [comment]
You have AAK Script installed right? 
If yes then I'm not sure what is the problem, I am not seeing the block screen, I scrolled up and down, and checked another random page, no block screen at all.

**Comment by ashutoshgoyal** [comment]
my bad.. AAK was unchecked.. very sorry for wasting ur time..will be careful in future..
