### ISSUE TITLE
userscloud.com

### ISSUE THREAD

**Issue by SBI-boy** [X01X012013/AdBlockProtector#24]
Some userscloud files are not possible to download on uploaders request

example url: https://userscloud.com/ctj41kx7k3fc
message returned: The publisher of this file doesnt allow adblock, please disable and Reload
thanks
PS: Using greasemonkey+ublock+eveything you recommended

**Comment by X01X012013** [comment]
Hi, This is patched into 1.2.3
```JavaScript
onEvent("load", function () {
    $("#dl_link").show();
    $("#adblock_msg").remove();
});
```

**Comment by SBI-boy** [comment]
This is strange, yesterday I downloaded from the main site the 1.1.4 version, wich I thought it was the last one, thanks anyways 👍 👍

**Comment by X01X012013** [comment]
@SBI-boy 
1.1.4 was the latest one yesterday, I updated it 4 times today to 1.2.4. The minor version (second number) changed because I did a rather large "kernel" library patch.
