### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by Sheiklan** [X01X012013/AdBlockProtector#26]
<img width="688" alt="adf ly" src="https://cloud.githubusercontent.com/assets/23268842/20023261/386dac0c-a2df-11e6-9dc2-183ff37b312d.PNG">

&nbsp;

Mirror: http://q.gs/

**Comment by mikhoul** [comment]
Just tried and I have no prob.em.

**Comment by X01X012013** [comment]
Hi, please provide a more specific link, their home page seems to work.

**Comment by mikhoul** [comment]
I tried few adfly links and they work here. 😽

**Comment by X01X012013** [comment]
There is no response for 5 days, I will close this issue now, please re-open it if needed.
