### ISSUE TITLE
vidlox.tv [NSFW], *.wetplace.com [NSFW], and *.pinkrod.com [NSFW]

### ISSUE THREAD

**Issue by rockyshaw** [X01X012013/AdBlockProtector#29]
http://vidlox.tv/embed-lopmspvqw2uq.html
http://m.wetplace.com/videos/69845/carolina-sweets-spreads-her-pussy-lips-invitingly-in-hardcore-action/#
http://m.pinkrod.com/videos/56066/latin-victoria-valencia-asks-her-fuck-buddy-to-shove-his-sturdy-love-stick-in-her-mouth/

**Comment by X01X012013** [comment]
Hi, all 3 websites are fixed in 1.2.14.

**Comment by X01X012013** [comment]
There is no response for 5 days, so I assume this fix worked. Let me know if there are any other issues.
