### ISSUE TITLE
Gmail, YouTube and other Google services

### ISSUE THREAD

**Issue by tosiara** [X01X012013/AdBlockProtector#30]
GMail stops loading in the middle, youtube video frame remains black, hangouts plugin does not load etc
Adding `https://*.google.com/*` into exclude resolves the issue

**Comment by X01X012013** [comment]
Hi, which browser are you using? Everything is working just fine here.

**Comment by mikhoul** [comment]
My guess he is using Firefox like me (the bug with JSbin), you should think to include support for Firefox ! :stuck_out_tongue_winking_eye:

**Comment by xxcriticxx** [comment]
firefox 49.0.2 i cant click on google apps :(

**Comment by X01X012013** [comment]
Sorry, we currently do not support FireFox, I will consider it in the future.

**Comment by mikhoul** [comment]
> Sorry, I currently do not offer support for FireFox, I will consider it in the future. 

You should since UBO, ABP, Reek all support Firefox, in meantime you should write it prominently on the download/installation page to stay away from the confusion.  🐸

**Comment by X01X012013** [comment]
I do have it on the installation page: 
> I will make that this project works on Chrome and Opera with Tampermonkey and Adblock Plus, I will try to offer support for other setups if I can.

**Comment by X01X012013** [comment]
https://github.com/X01X012013/AdBlockProtector/issues/23#issuecomment-258955091

**Comment by tosiara** [comment]
@X01X012013 Yes, I also one of those who use Firefox... And all worked fine until yesterday

**Comment by X01X012013** [comment]
@tosiara As you can see in those screenshots, it works fine on my Firefox.

**Comment by X01X012013** [comment]
Please post in #32 for further discussions.
