### ISSUE TITLE
Outlook.com -> ":-( Something went wrong"

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [X01X012013/AdBlockProtector#32]
Hi there,

Since I checked for an update and updated the script today, it causes outlook load failure when going to my inbox.

I tried disabling uBlock + uMatrix and other scripts, tried reinstalling it and reek in the order suggested on your website, however the issue remains even with just adblockprotector enabled.

Any assistance you could provide would be appreciated, thanks.

Edit: Firefox 49.0.2 64-Bit, uBlock github, Greasemonkey 3.9, script is at version 2.0.3 and additionally I was unable to use the edit button on this post until unchecking AdBlockProtector.

Thanks for your hard work!

**Comment by X01X012013** [comment]
Hi, I cannot reproduce this issue. Outlook works just fine for me. 
![screenshot](http://i.imgur.com/lTLyEgj.png)

**Comment by xxcriticxx** [comment]
@X01X012013 try it with ublock o and greasemonkey

**Comment by X01X012013** [comment]
@xxcriticxx Sorry, that setup is not officially supported for now.

**Comment by xxcriticxx** [comment]
@X01X012013 yes i know but thats what makes in not compatible

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I'm sorry maybe there is a misunderstanding here, as I mentioned, it is still broken even WITH uBlock + uMatrix + all other scripts disabled, can you try loading the inbox from US proxy?

It also breaks https://www.videolan.org/ drop down menus on the top ribbon. I don't know why you can reproduce this issue.

Can you please elaborate on what is officially supported? Last night your instruction website made no mention of what adblocker.

**Comment by xxcriticxx** [comment]
@L-a-n-g-o-l-i-e-r-s your greasemoneky is on and your adblock script is on. they both have to be gray to be off

**Comment by X01X012013** [comment]
@L-a-n-g-o-l-i-e-r-s 

Hi, currently supported setup: 

Browser: Chrome and Opera
Script host: Tampermonkey
AdBlocker: Adblock Plus

If my script works on other setups, that's great, if it doesn't, sorry but I am not planning to expand compatibility for now.

**Comment by X01X012013** [comment]
@L-a-n-g-o-l-i-e-r-s 
I did mention it in the instruction page, under "How do I use it?"

>I will make sure that this project works on Chrome and Opera with Tampermonkey and Adblock Plus

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
But how come it worked until a recent update?

**Comment by X01X012013** [comment]
@L-a-n-g-o-l-i-e-r-s 
I'm not sure, everything works fine in my tests.
