### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by luckyearl** [X01X012013/AdBlockProtector#33]
Hi
The script was working great until yesterday, today NDTV detecting adblocker
url :http://www.ndtv.com/video/live/channel/ndtv24x7
Please help

**Comment by X01X012013** [comment]
Hi, this website was in AAK 9.9 patch note, I did a quick test and didn't look deeper, sorry about that. The fix is now back into AdBlock Protector 2.0.4.

**Comment by luckyearl** [comment]
Thats great working again
thank you so much
