### ISSUE TITLE
detectadblock.com

### ISSUE THREAD

**Issue by Eva850** [X01X012013/AdBlockProtector#36]
This site detects adblock. 
Ublock Origin with default configuration + AAK list + Adblock protector
Tampermonkey + AAK script + Adblock protector.
This rule prevents from detecting:
`@@||www.detectadblock.com/ads.js$script,domain=www.detectadblock.com`

**Comment by X01X012013** [comment]
Hi, I think this website is handled by AAK. 
![screenshot](http://i.imgur.com/LpPgwVM.png)

**Comment by Eva850** [comment]
Reinstalling Ublock Origin and subscribing filters fixed this issue. Thank you.
