### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by Eva850** [X01X012013/AdBlockProtector#37]
They changed anti adblock. It forces to wait before download.
Chrome
Tampermonkey + AAK + Adblock Protector
Ublock Origin + AAK list + Adblock Protector list
![apkmirror](https://cloud.githubusercontent.com/assets/20646455/20574583/7f092f4e-b1b5-11e6-90e3-7c948d7ebfff.png)

**Comment by X01X012013** [comment]
Hi, I cannot reproduce this issue, please try to update all scripts and lists. 
![screenshot](http://i.imgur.com/i71wETp.png)

**Comment by Eva850** [comment]
Hello, I can't make it working on Chrome. On Firefox it works without problems. What is Yours exact configuration of Chrome?

**Comment by X01X012013** [comment]
@Eva850 
![screenshot](http://i.imgur.com/auPVRW4.png)
![screenshot](http://i.imgur.com/6tuZA9z.png)

**Comment by Eva850** [comment]
Hello, I still can't make it working on Chrome. On Firefox it works, so I will close this issue
