### ISSUE TITLE
firefox support?

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#39]
any news on firefox support for your script?

**Comment by X01X012013** [comment]
Hi, FireFox is not officially supported. For all supported setup, please read https://x01x012013.github.io/AdBlockProtector/#how

**Comment by ghajini** [comment]
Hi @jspenguin2017, if Firefox CSP is issue for release of ublock protector for firefox then see if `angelsl` comment

`https://github.com/violentmonkey/violentmonkey/issues/173`
p.s- don't block me if this hurts your repo rules,I will simply disregard

**Comment by jspenguin2017** [comment]
AFAIK Firefox does have a way to inject code: export the function then invoke it. 
I'm not going to release a Firefox version because Chrome version alone is already too much work. And you are using Adguard aren't you? Why do you care? It's available for Firefox or not, it's not going to work nicely with Adguard.

**Comment by ghajini** [comment]
Many users want Firefox version of ublock protector(see ur repo for Firefox tag e.g) .....today I see angelsl comment(of overriding CSP) in violentmonkey thread so I  reported here.....see if that angelsl comment really helps you......yes I definitely use adguard 70% of time.....

**Comment by jspenguin2017** [comment]
I knew nuking CSP works, but that introduces security issues, so angelsl's comment does not help. 
I don't feel like providing support for Firefox, that's all. If I want to support Firefox, I would have found good workarounds for the limitations of the browser. Beside, websites that use CSP is quite limited, things would work properly most of the time. 
My extension is free for you to use, so you are not allowed to complain. Someone else is kind enough to offer more does not mean I have to do that too.
