### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by Eva850** [X01X012013/AdBlockProtector#4]
Hi, I have a problem with site apkmirror.com
It seems that they have changed anti-adblock script, because Anti Adblock Killer does not work, despite that this site is on supported list.
Screenshot: https://drive.google.com/open?id=0B6g6Av7dwyPFOFNaZTV6d3BLdTg
Firefox + Adguard + Greasemonkey
This rule works for me: 
`||apkmirror.com/wp-includes/js/jquery/jquery.js*$domain=apkmirror.com`
But I know that it is not a good way to do it.

**Comment by X01X012013** [comment]
Hi there, I could not reproduce this issue. 
![screenshot](http://i.imgur.com/hqJdzX0.png)
The download button works fine without any wait time. 
Thanks for the rule, it may help other people who are experiencing the same thing as you.
