### ISSUE TITLE
[Discussion] Should we merge AAK into this project? Reek seems to be gone again. 

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#44]
It's been 3 month since the last time AAK is updated. It's no easy task to manage large project like that, and I won't promise that I can compile solutions in a timely manner neither. But with the help of the community, we can make this possible. 
I would need A LOT of help from the community to merge AAK into here, and there might be a lot of work done twice, but on the flip side, we will be able to compile community solutions easily and use less horrible hacks when a website breaks because of AAK. 

Please post your opinion below, I will make final decision before the end of February.

**Comment by xxcriticxx** [comment]
@X01X012013 thats great idea!

**Comment by szymon1118** [comment]
@X01X012013 Great but I can't help regularly. If I could, I will help :smiley:.

**Comment by xxcriticxx** [comment]
@mikhoul, @F4z, @MajkiIT, @azet12, @uBlock-user, @uBlock-user, @maynak00, @phuc365, @Piter432, @FadeMind  and rest any input on this?

**Comment by Piter432** [comment]
Sure, why not? 😃

**Comment by X01X012013** [comment]
We are in a "pick one" situation: 

* Up and running tomorrow
* Good code quality
* Stable and doesn't break things

**Comment by MajkiIT** [comment]
Yes, it's good idea.

**Comment by X01X012013** [comment]
@xxcriticxx @MajkiIT Would you guys willing to switch to Tampermonkey? It is available for Firefox. Greasemonkey's broken security policies are making the development process very difficult.

**Comment by MajkiIT** [comment]
@X01X012013 Ok. I will do it. Give mi 5 minutes.

**Comment by xxcriticxx** [comment]
@X01X012013 yes no problem

**Comment by MajkiIT** [comment]
@X01X012013 done

**Comment by X01X012013** [comment]
I chose 1. 
Can someone test it?

**Comment by mikhoul** [comment]
@X01X012013 

Not really,

It would be cool but it should support all Browsers and all Userscript hosts including Greasemonkey.

Even if you don't personally like it Gresemonkey is **MORE** powerful than Tampermonkey, I can do many things with GM that TM can't do, but tha's not the point. A Userscript should NOT be made to use only one host. Encouraging Diversity and choices is the best thing for the users and community.

**If you want to have some Improvement or Feature in Greasemonkey join the dev here:** https://groups.google.com/forum/#!starred/greasemonkey-dev/K6IyDUWnTQc

Anthony is going to redesign Greasemonkey from the ground to adhere to the WebExtension with more features than TamperMonkey.

Let me know at the end your decision :smile_cat: 


**Regards** :octocat:

**Comment by X01X012013** [comment]
@mikhoul Sorry I don't have time to develop for GM, it hides all errors and it's overall a pain. You are free to use something else if you just love GM.

**Comment by X01X012013** [comment]
I pasted AAK code after AdBlock Protector's code, you should expect the new script to behave like before. I will clean up the code later, and we will stay in sync with AAK if Reek comes back. 
The difference will be that we will drop support for some scripts hosts and browsers.

**Comment by uBlock-user** [comment]
As long as the maintainer is active and participating in the issue tracker, go ahead and do it.

**Comment by X01X012013** [comment]
@uBlock-user I will monitor Issues of this repository only, I won't compile those 600+ issues of AAK unless someone helps me.

**Comment by uBlock-user** [comment]
@X01X012013 Obviously! That repo is out of control and going berserk.
