### ISSUE TITLE
Update request for AAK List

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#46]
We have to remove something from AAk script because shows to much ads on wp.pl

**Comment by xxcriticxx** [comment]
@MajkiIT @F4z what do we have to remove?

**Comment by X01X012013** [comment]
The domain isn't included in Script, I didn't find exact match from List, but some generic stuff might be causing problem. I can't access the website so I can't check.

**Comment by X01X012013** [comment]
And I'll do some cleaning for AAK code, but because it has 9000 lines, I will need some custom tool (probably in C#) to automate the process... 
I also want to have a jQuery-like core library. This will make developing easier, so I don't need to keep modifying the huge 5000 lines script... Or maybe it will be shorter when I clean it up?

**Comment by xxcriticxx** [comment]
I think you can ask @szymon1118 here for help with C

**Comment by X01X012013** [comment]
C#, Not C, no worries, I know C# pretty well. Not as well as JavaScript but enough for these tools.

**Comment by xxcriticxx** [comment]
@X01X012013 please remove `@@||wp.pl^$script,image` from the old AAK code

**Comment by X01X012013** [comment]
Done. Removed from 5.4, can you test if it has side effects?

**Comment by xxcriticxx** [comment]
tmonkey is showing me i am on version 5.8

**Comment by X01X012013** [comment]
Sorry, I meant List v5.4
Yea, i might need to keep the versions in sync...

**Comment by xxcriticxx** [comment]
great idea :)

**Comment by MajkiIT** [comment]
@X01X012013 
For my opinion you can remove:
! tvn24.pl
@@||admin.brightcove.com^$object-subrequest,domain=tvn24.pl
! filmweb.pl
@@||ad.filmweb.pl/adbanner/reklamy/adx.js$script
! onet.pl
! https://github.com/reek/anti-adblock-killer/issues?q=onet.pl
||lib.onet.pl^*/adp/adp.js$script
! kozaczek.pl (isAdBlockActive=false;)
! https://github.com/reek/anti-adblock-killer/issues/414
@@||kozaczek.pl/js/ads.js$script,domain=kozaczek.pl
! epoznan.pl/wtkplay.pl
! https://github.com/reek/anti-adblock-killer/issues/525
@@||play.wtk.insys.pl/Scripts/InsysPlayer.v0.1.0/adTest.png$image
@@||ad.adview.pl/ad/$xmlhttprequest,domain=play.wtk.insys.pl

**Comment by X01X012013** [comment]
@MajkiIT OK, I'll patch it.

**Comment by X01X012013** [comment]
It is patched into List 5.5, can someone test these websites to make sure we didn't break anything? 

wp.tv
wp.pl
tvn24.pl
filmweb.pl
onet.pl
kozaczek.pl
epoznan.pl
wtkplay.pl

**Comment by MajkiIT** [comment]
@X01X012013 Ok I will check it

**Comment by MajkiIT** [comment]
@X01X012013 everything is OK

**Comment by X01X012013** [comment]
Nice!

**Comment by MajkiIT** [comment]
Also remove
@@||vstrim.pl/js/ads.js$script,domain=vstrim.pl --- dead
@@||zeberka.pl/js/ads.js$script -- not use this script
@@||squid.gazeta.pl/info/squid/fprint.js$script,domain=wyborcza.pl|gazeta.pl -- not use this script, new solution polish filters 
@@||squid.gazeta.pl/sqpwgl/pwfpl$xmlhttprequest,domain=wyborcza.pl|gazeta.pl -- not use this script, new solution polish filters 
@@||squid.gazeta.pl/sqpwgl/pwif$subdocument,domain=wyborcza.pl|gazeta.pl -- not use this script, new solution polish filters

**Comment by X01X012013** [comment]
@MajkiIT Is the new solution in Easy List? If not, please post the new solution.

**Comment by MajkiIT** [comment]
@X01X012013 No I find old filters in AAK. Post new solution?

**Comment by X01X012013** [comment]
@MajkiIT If the solution isn't in Easy List, then please post them.

**Comment by X01X012013** [comment]
Notes for devs: 
```
! Safe to remove: 
@@||vstrim.pl/js/ads.js$script,domain=vstrim.pl
```
```
! Test in progress: 
@@||zeberka.pl/js/ads.js$script
@@||squid.gazeta.pl/info/squid/fprint.js$script,domain=wyborcza.pl|gazeta.pl
@@||squid.gazeta.pl/sqpwgl/pwfpl$xmlhttprequest,domain=wyborcza.pl|gazeta.pl
@@||squid.gazeta.pl/sqpwgl/pwif$subdocument,domain=wyborcza.pl|gazeta.pl
```

**Comment by X01X012013** [comment]
@MajkiIT Hi, I am still waiting for your response, can you post your new solutions?

**Comment by MajkiIT** [comment]
`@@||cdnv.gazeta.pl/ad/banner/_adsense_/_adserver/_adview_.ad.json$xmlhttprequest,domain=gazeta.pl`
`@@||video.gazeta.pl/cdn/ads/ad/banner/_adsense_/_adserver/_adview_.ad.json$xmlhttprequest,domain=video.gazeta.pl`

Page vstrim.pl is dead.

Zeberka.pl not not use any script to detect adblock.

**Comment by X01X012013** [comment]
I will have a look tomorrow, don't worry, I'm still here.

**Comment by MajkiIT** [comment]
@X01X012013 Ok thanks.

**Comment by X01X012013** [comment]
This looks like still valid, it could be used by other websites: 
```
@@||zeberka.pl/js/ads.js$script
```
The rest are dead and removed. 
I'm testing your new solutions.

**Comment by X01X012013** [comment]
@MajkiIT Thanks for your contribution! Here is the commit: https://github.com/X01X012013/AdBlockProtector/commit/99d5e0ecbf766ca60769b9dc84d5dfc8519c669b

**Comment by MajkiIT** [comment]
@X01X012013 Also thank you.
