### ISSUE TITLE
[Testers Needed]New generic FuckAdBlock blocker

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#47]
Hi, we have added generic FuckAdBlock blocker to 5.25, to address these issues: 

1. AAK's fake FAB is somewhat outdated. 
2. Writing into AAK's fake FAB will cause an error, we have changed that to make writing silently fail. We also have a more stealthy mode that can be applied to specific domains. 
3. We now can handle multiple `onNotDetected` event handlers, up from just 1. 

I did some basic testings and it seems to work fine, can everyone goes to websites he frequents to see if everything works?

**Comment by xxcriticxx** [comment]
@X01X012013 did you fix blockAdBlock and unreachable code after return statement?

**Comment by X01X012013** [comment]
@xxcriticxx 
If you mean BlockAdBlock by the same author as FuckAdBlock, then yes, I took care of that. I did patch some AAK code, and the way I did it was adding a return so code after won't run. It is just temporary. I'm adding a flag to control if AAK code should be run at all, I will add a config page to give you control over it soon^tm .

**Comment by xxcriticxx** [comment]
hero are some logs



[alltube.tv-1486950089709.txt](https://github.com/X01X012013/AdBlockProtector/files/769871/alltube.tv-1486950089709.txt)
[freedisc.pl-1486949955783.txt](https://github.com/X01X012013/AdBlockProtector/files/769870/freedisc.pl-1486949955783.txt)

**Comment by X01X012013** [comment]
@xxcriticxx What are these logs for?

**Comment by xxcriticxx** [comment]
Websites I frequent visit logs are console errors

**Comment by X01X012013** [comment]
@xxcriticxx 
Console outputs are usually not needed. If something is not working, please explain what is wrong.

**Comment by X01X012013** [comment]
Everything seems to be fine.
