### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#48]
![capture](https://cloud.githubusercontent.com/assets/15007183/22896540/90a6ac08-f1ee-11e6-8b98-3c64be172a6b.PNG)

@X01X012013 owner of this website told us he will change div name daily to go around our filters. can you add this to your script to block this ad block?

Test URL: http://www.elektroda.pl/rtvforum/topic3295766.html?l=en

**Comment by X01X012013** [comment]
OK I'll have a look. 

Notes: 
`window.google_ad_status = 1;`

**Comment by xxcriticxx** [comment]
paging @F4z and @MajkiIT

**Comment by X01X012013** [comment]
Notes for devs: 
Offending function: 
```JavaScript
if ($(window).on("load resize", function() {
        var o = $(".topbar-wrap"),
            e = $(window);
        topbarHeight = o.height(), lastWindowTopScroll = window.pageYOffset || document.documentElement.scrollTop, e.width() > 767 ? e.off("scroll.showHideTop") : e.on("scroll.showHideTop", hideTopOnScroll), o.css("top", 0)
    }), document.querySelectorAll(".eb88a7fd7fa2f20fffeae422").length > 0) {
    var adBlockTest = document.createElement("div");
    adBlockTest.innerHTML = "&nbsp;", adBlockTest.className = "adsbox ads adsframe ad ads-box ads-frame", document.body.appendChild(adBlockTest), window.setTimeout(function() {
        0 === adBlockTest.offsetHeight && (document.querySelectorAll(".eb88a7fd7fa2f20fffeae422")[0].style.display = "block"), adBlockTest.remove()
    }, 100)
```

**Comment by X01X012013** [comment]
Found weak point: setTimeout.

**Comment by xxcriticxx** [comment]
@X01X012013 good news

**Comment by X01X012013** [comment]
@xxcriticxx OK, done. Patched into 5.33, along with a patch to core library to fix a critical flaw.

**Comment by xxcriticxx** [comment]
@X01X012013 will update and test

**Comment by xxcriticxx** [comment]
@X01X012013 tm doesnt find any updates

**Comment by xxcriticxx** [comment]
@X01X012013 yep works thx!

**Comment by X01X012013** [comment]
@xxcriticxx I addressed delayed update issue in 3.34, if you want to re-install Script (and List), next time the update should be faster. Make sure to refresh the homepage to load the new version.

**Comment by xxcriticxx** [comment]
@X01X012013 done i am on 3.34 now

**Comment by X01X012013** [comment]
Good, let's close this issue now.
