### ISSUE TITLE
list sorting

### ISSUE THREAD

**Issue by MajkiIT** [X01X012013/AdBlockProtector#49]
Maybe can you sort filters on yours list? I do it. Please see in your free time
[aak2.txt](https://github.com/X01X012013/AdBlockProtector/files/773849/aak2.txt)

**Comment by X01X012013** [comment]
Hi, the list is created by a compiler. If you have time, please implement sorting into the compiler.

**Comment by X01X012013** [comment]
Why do you think sorting is necessary? You would need `Ctrl+F` anyway.

**Comment by MajkiIT** [comment]
I think it's better to have order. It's yours filters and you do what you want. I just suggested.

**Comment by X01X012013** [comment]
I don't see the benefit of sorting alphabetically. If we ever decide to sort it, it needs to be done in the compiler, not manually.
