### ISSUE TITLE
businesstoday.in

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#5]
http://www.businesstoday.in/markets/stocks/sensex-nifty-may-hit-fresh-lifetime-highs-if-gst-bill-gets-through-parliament/story/235698.html

**Comment by X01X012013** [comment]
Hi there, this is fixed in 1.0.56. 
Let me know if it doesn't work. 

Lock checkAds to an empty function.

**Comment by ashutoshgoyal** [comment]
Working fine. Thanks.
