### ISSUE TITLE
wp.tv, wtkplay.pl

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#50]
Test URLs:
http://wp.tv/i,kwiaciarnie-przezywaja-prawdziwe-oblezenie,mid,1997828,cid,4051,klip.html?ticaid=518a01
http://wtkplay.pl/video-id-30561-uniwersytet_otwarty

Notes for devs: 
wp.tv -> container class is `.player__container`
wtkplay.pl -> `var can_run_ads = true;`

**Comment by xxcriticxx** [comment]
@X01X012013 on ver 5.39 i am getting adblock on wp.tv

**Comment by X01X012013** [comment]
@xxcriticxx 
Yes, I am aware of that, it's currently work in progress.

**Comment by X01X012013** [comment]
Both fixed in 5.42
