### ISSUE TITLE
Breaks DuckDuckGo search results

### ISSUE THREAD

**Issue by SteegHobland** [X01X012013/AdBlockProtector#51]
With the AdBlockProtector enabled, I can't see any search results. When disabled, I see search results. Tried on Firefox 51.0.1 on Windows XP, and 50.1.0 on Mint 17.1

**Comment by X01X012013** [comment]
Hi, it works fine for me. Which script host and AdBlocker are you using? 
![image](https://cloud.githubusercontent.com/assets/7283682/23007379/968e710e-f3c5-11e6-91db-954a0b82a4cf.png)

**Comment by SteegHobland** [comment]
Greasemonkey 3.9 and Adblock Plus 2.8.2
A script I'm using, Anti-Adblock Killer | Reek 10.0, may also be relevant.

**Comment by X01X012013** [comment]
Hi, Greasemonkey is not supported, please use Tampermonkey as script host. 
Also, a patch version of AAK is integrated into AdBlock Protector, so you don't need both.

**Comment by SteegHobland** [comment]
Oh, I didn't expect that should be an issue. Is there a way to have Tampermonkey import installed scripts automatically?

**Comment by X01X012013** [comment]
I'm not sure about this.

**Comment by SteegHobland** [comment]
Thanks for the help!

**Comment by X01X012013** [comment]
Alright, I'll close this issue now.
