### ISSUE TITLE
[Announcement] Repository restructure

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#53]
Hi, we are restructuring the repository for new compilers, during this time, you will not be able to update your Script or List, and when finished, you would need to re-install Script and List.

**Comment by X01X012013** [comment]
Update 1: 
New Core library is ready. All generic protectors rewritten, tests needed. 
3344 lines of specific code to clean up.

**Comment by xxcriticxx** [comment]
@X01X012013 i will test tomorrow

**Comment by xxcriticxx** [comment]
i cant pull anything to test. how can i update?

**Comment by MajkiIT** [comment]
@X01X012013 On version 6 I have problem with video on pages wp.pl etc. For example here http://wp.tv/i,prognoza-pogody-na-17-lutego,mid,1997971,cid,2303759,klip.html . I see adblock alert or video is not loading. On version 5.42 it's OK

**Comment by X01X012013** [comment]
@MajkiIT I am aware of this, it will be fixed very soon.

**Comment by X01X012013** [comment]
@MajkiIT This should be fixed in 6.4
2400 lines to go #progress

**Comment by xxcriticxx** [comment]
@X01X012013 we appreciate your work!

**Comment by X01X012013** [comment]
@xxcriticxx Thanks :D

**Comment by X01X012013** [comment]
Update 2: We are only 1500 lines away! 

If you are wondering why we are making these big changes: 

This change will add a solid foundation to the Script, it will also address a few sticky issues:

First, this change will fix a huge flaw in AAK's domain comparison logic. Period (`.`) means match everything except new line in regular expression, and Reek escaped none of them. Our new comparison logic doesn't use regular expression, so it will be faster while fixing this flaw. 

Second, we are dropping compatibility checks, by dropping support for Greasemonkey, we can significantly shorten the code length while improving performance. 

Last but not least, we improved the `beforescriptexecute` hack of AAK, rules that rely on this should be significantly faster.

**Comment by xxcriticxx** [comment]
@X01X012013 links please when you done

**Comment by MajkiIT** [comment]
@X01X012013 Ok, thank you for your help.

**Comment by X01X012013** [comment]
@xxcriticxx @MajkiIT 
Hi guys, restructure is done! Thank you for your patience :D
Let me know if there are any issues.

**Comment by X01X012013** [comment]
Also our homepage got a bright new look, with a chat board added to it!

**Comment by X01X012013** [comment]
We are aware that settings page is really buggy, we are working on a fix.

**Comment by X01X012013** [comment]
Hi guys, it looks everything is stable now, please make sure to refresh our webpages to load the latest builds, and update both Script and List. If you are upgrading from 5.x, you will need to manually re-install this project.
