### ISSUE TITLE
emuparadise.me

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#54]
ad block

https://www.emuparadise.me/Sony_Playstation_ISOs/E.T._-_The_Extra-Terrestrial_-_Interplanetary_Mission_[NTSC-U]/36853-download

![capture](https://cloud.githubusercontent.com/assets/15007183/23108458/93584e6a-f6db-11e6-9f9b-5e56970b81df.PNG)

**Comment by X01X012013** [comment]
Hi, I'm not getting anything, can you post a bigger image along with your setup? 
![screenshot](http://i.imgur.com/mcwV5Iu.png)

**Comment by X01X012013** [comment]
Hi, this is fixed in 6.8. 
Looks like all they did is to show a box if one of the 3 ad boxes are hidden, we can just remove the element, no further action needed. 
```JavaScript
if (a.domCmp(["emuparadise.me"])) {
    //Remove element
    a.always(function () {
        a.$("h2:contains('Bandwidth is expensive')").parent().remove();
    });
}
```

**Comment by xxcriticxx** [comment]
you going make template for future use? or just post like this?

**Comment by X01X012013** [comment]
Yea, future use, so we don't need to dig a hole in Git history when we need to find something.

**Comment by xxcriticxx** [comment]
thx

**Comment by X01X012013** [comment]
So this looks like fixed, I'll close this issue now.
