### ISSUE TITLE
allmusic.com, sidereel.com 

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#55]
link - http://www.allmusic.com/

link - http://www.sidereel.com/

**Comment by X01X012013** [comment]
Thanks for your report, I'll have a look. 

Notes for devs: 

http://www.allmusic.com/
Obfuscated code + anti-right-click
Random tag name... ?! Surprised that browsers accept that...

**Comment by X01X012013** [comment]
Hi, http://www.allmusic.com/ is fixed in 6.15, and I don't see what's wrong with http://www.sidereel.com/ , do you have a more specific link?

**Comment by uBlock-user** [comment]
How did you patch `allmusic.com` ? By defusing `setTimeout` calls, it doesn't work in uBO. So I'm wondering. 

Secondly, `sidereel.com` has the anti adblock as allmusic.com, I can reproduce from the link I gave you, same anti adblock screen appears.

**Comment by X01X012013** [comment]
@uBlock-user 

`a.filter("setTimeout", /\_0x6176x12/);` It works for me, I'm not sure how you do it with uBlock Origin. 

For `sidereel.com`, is it on the home page? I'm not seeing anything.

**Comment by uBlock-user** [comment]
Yes it is. Secondly, `allmusic.com##script:inject(setTimeout-defuser)` is done in uBO, unfortunately, that doesn't work but `allmusic.com##script:inject(abort-on-property-read.js, setTimeout)` stops the screen from appearing but also breaks the website.

> For `sidereel.com`, is it on the home page?

Yes it is. Make sure you're not blocking cookies from either of the websites as that also works.

**Comment by X01X012013** [comment]
Try `(setTimeout-defuser, _0x6176x12)`
Looks like uBlock filter has this line: 
`allmusic.com##script:inject(abort-on-property-write.js, _0xe367)`
They seems to be using closure to dodge this. 

I'm not blocking cookies. 
![image](https://cloud.githubusercontent.com/assets/7283682/23137298/855e4a3e-f75e-11e6-9c94-8360b9498951.png)

**Comment by uBlock-user** [comment]
For sidereel.com, this works - `sidereel.com##script:inject(abort-on-property-read.js, setTimeout)` I can't see anything broken. 

I tested that filter, but to no effect.

**Comment by X01X012013** [comment]
I can't reproduce them, everything works fine with latest AdBlock Protector for me.

**Comment by X01X012013** [comment]
What about `(setTimeout-defuser.js, _0x6176x12)`?

**Comment by uBlock-user** [comment]
yes, I tried that, doesn't work either.

**Comment by X01X012013** [comment]
Hum, that's interesting, have you tried our Userscript?

**Comment by uBlock-user** [comment]
I'm sure that will work, but I do not want to run it for a single website.

**Comment by X01X012013** [comment]
Unfortunately, I would not be able to help you unless you are using our project. I will close this issue now.

**Comment by uBlock-user** [comment]
@X01X012013 `allmusic.com` is back with his anti adblock overlay, seems they're keeping track of this issue tracker and countering your patches.

**Comment by X01X012013** [comment]
They probably randomized the name... We need a more solid solution...

**Comment by uBlock-user** [comment]
I'm using `||allmusic.com^$inline-script`. Works fine. I have yet to see anything broken.

**Comment by uBlock-user** [comment]
This is where we truly need `BeforeScriptExecute` to mitigate such notorious websites.

**Comment by X01X012013** [comment]
Yea... but Chromium guys seem to not have plans for it... Maybe... maybe we can patch it in... ?

**Comment by X01X012013** [comment]
They changed the function name to "_0xf57cx1". I'll see if blocking all in-line scripts works.

**Comment by uBlock-user** [comment]
Can't you create a scriptlet and inject it via the script ? 

> I'll see if blocking all in-line scripts works.

I have already tested that, so obviously that works, which is already established, what I'm not sure is what and if it breaks parts of website or not. I haven't found any to be broken, so if you could check that out, that'd be nice.

**Comment by X01X012013** [comment]
By "works", I mean prevent block screen while not breaking anything else. I tested it, seems fine, I added it to List. 
I cannot change uBO's scriptlets.

**Comment by X01X012013** [comment]
`beforescriptexecute` event needs to be dispatched by the browser, there is no way I can intercept script execution with Userscript.

**Comment by uBlock-user** [comment]
Chrome officially doesn't send any information to the webRequest API when a WebSocket connection is established, so a contentscript.js was created by gorhill and injected  - https://github.com/gorhill/uBO-Extra/blob/master/contentscript.js

I'm wondering if you could do the same for `BeforeScriptExecute`. Any thoughts ?

**Comment by X01X012013** [comment]
@uBlock-user What he did is patching `WebSocket` so the script that runs is using the fake `WebSocket` which grant uBO the control over it. However, parsing and running script is under the control of the browser, it does not use any API exposed to `window`. The only way to intercept script execution is to patch the browser itself.

**Comment by X01X012013** [comment]
BTW, uBO does need to request the permission for `unsafeWindow`.

**Comment by X01X012013** [comment]
uBO does request permission to inject the script: 
https://github.com/gorhill/uBlock/blob/8dd6559759ffe929a881335d4f1206c6ff717c3d/platform/opera/manifest.json
```
    "content_scripts": [
        {
            "matches": ["http://*/*", "https://*/*"],
            "js": ["js/vapi-client.js", "js/contentscript.js"],
            "run_at": "document_start",
            "all_frames": true
        },
        {
            "matches": ["http://*/*", "https://*/*"],
            "js": ["js/scriptlets/subscriber.js"],
            "run_at": "document_idle",
            "all_frames": false
        }
    ]
```

It would work with TM, it should be slightly faster with uBO's direct injection.

**Comment by uBlock-user** [comment]
Yes, uBO itself does have all the permissions. 

It would work with TM, it should be slightly faster with uBO's direct injection.

>So is it possible ?

**Comment by X01X012013** [comment]
@uBlock-user It is possible to patch `WebSocket` with TM instead of uBO, yes. If you mean adding `beforescriptexecute` event, then no, we have no access to browser internals.

**Comment by uBlock-user** [comment]
> we have no access to browsers' internal functions.

That's a real shame :(

**Comment by X01X012013** [comment]
There is really no reasonable way to allow JavaScript to modify native code. I don't have a computer that is powerful enough to recompile Chromium, and even if I have one, I probably won't be able to patch it since I'm not good at C++. 
FireFox still have that event, but the devs are thinking about dropping it. Looks like we have no other choice than living without `beforescriptexecute` event.

**Comment by uBlock-user** [comment]
`sidereel.com` is acting up again for me. Can you check it out ?

**Comment by uBlock-user** [comment]
FYI - `sidereel.com` is acting up again today. I'm using `sidereel.com##script:inject(abort-on-property-read.js, setTimeout)`. It does break one or two things, however nothing major.

**Comment by X01X012013** [comment]
I'll open a new issue for this.
