### ISSUE TITLE
gs24.pl - Disable autoplay

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#56]
@X01X012013 can you see if you can disable auto play on video?

sample link:

http://www.gs24.pl/wiadomosci/szczecin/a/straz-miejska-w-szczecinie-sprawdzi-czym-palimy-w-piecu,11803953/

**Comment by X01X012013** [comment]
It's possible, but it's not that easy to do and it might not be the behavior that everyone want. I will think about this.

**Comment by xxcriticxx** [comment]
@X01X012013 can the movie download in background and all the user does push play if they want to watch it?

**Comment by X01X012013** [comment]
Notes for devs: 
```JavaScript
a.win.setInterval(function(){
  a.$("video").each(function(){
      this.pause();
  });
}, 500);
```
This is the prove of concept that it is possible, how to properly call `pause()` is another question...

**Comment by X01X012013** [comment]
We might need a mutation observer here... Might add `a.observeMutation()` as a Core function.

**Comment by X01X012013** [comment]
@xxcriticxx Good news! This is added to 6.20! And it's toggle-able in settings page.

**Comment by X01X012013** [comment]
In case you are curious how it is done: 
```JavaScript
    //===GS24 mods===
    if (a.mods.GS24_NoAutoplay) {
        //Watch video tag insertion
        a.observe("insert", function (node) {
            if (node.tagName === "VIDEO") {
                node.onplay = (function () {
                    //We need to pause twice
                    let playCount = 2;
                    return function () {
                        playCount--
                        this.pause();
                        //Paused twice, detach event handler
                        if (playCount === 0) {
                            this.onplay = null;
                        }
                    }
                })();
            }
        });
    }
```

**Comment by X01X012013** [comment]
Any feedback on this? If this works for you please close this issue.

**Comment by xxcriticxx** [comment]
all good
