### ISSUE TITLE
epiotrkow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#57]
ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/23146682/ef27bde0-f7a6-11e6-8c84-f21dc3fbe596.PNG)

**Comment by X01X012013** [comment]
Fixed in 6.18.
`a.bait("div","#adboxx");`

**Comment by xxcriticxx** [comment]
div name changes very often on this page

**Comment by X01X012013** [comment]
Even the bait div?

**Comment by xxcriticxx** [comment]
let check in few days

**Comment by X01X012013** [comment]
OK, I'll leave this issue open for 2 weeks.
