### ISSUE TITLE
redundant rules

### ISSUE THREAD

**Issue by MajkiIT** [X01X012013/AdBlockProtector#58]
fox.com.tr#@#.text-ad-links has been made redundant by fox.com.tr#@#.text-ad-links
fox.com.tr#@#.text-ads has been made redundant by fox.com.tr#@#.text-ads
fox.com.tr#@#.text_ads has been made redundant by fox.com.tr#@#.text_ads
fox.com.tr#@#.text_ad has been made redundant by fox.com.tr#@#.text_ad
fox.com.tr#@#.textAd has been made redundant by fox.com.tr#@#.textAd
fox.com.tr#@#.text-ad has been made redundant by fox.com.tr#@#.text-ad
fox.com.tr#@#.pub_728x90 has been made redundant by fox.com.tr#@#.pub_728x90
fox.com.tr#@#.pub_300x250m has been made redundant by fox.com.tr#@#.pub_300x250m
fox.com.tr#@#.pub_300x250 has been made redundant by fox.com.tr#@#.pub_300x250

||adage.com/assets/js/min/adBlockDetector.js$script has been made redundant by /AdblockDetector.js$script
@@||politiken.dk/static/content/js/ads.js$script has been made redundant by @@||politiken.dk/*ad$script

**Comment by X01X012013** [comment]
Looks like the rules don't work at all on `fox.com.tr`...

**Comment by X01X012013** [comment]
`/adblockdetector.` is part of Easy List, I'll remove both entries.

**Comment by X01X012013** [comment]
Thanks for your contribution!
