### ISSUE TITLE
zrabatowani.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#59]
ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/23193979/81204d7a-f879-11e6-82ee-02a61460c203.PNG)

**Comment by X01X012013** [comment]
Ops, there is a flaw in the Core library, 51 rules should be fixed with this new update... [Facepalm]

For this website, this new Script rule will do, it is added to 6.25: 
```JavaScript
if (a.domCmp(["zrabatowani.pl"])) {
    //Set cookie
    a.cookie("adblockAlert", "yes");
}
```

**Comment by X01X012013** [comment]
Looks like things are going well here, I'll close this issue now.
