### ISSUE TITLE
Have I installed the script correctly?

### ISSUE THREAD

**Issue by rahulraj80** [X01X012013/AdBlockProtector#6]
System: MacBook Air 10.10.5, Safari 9.1.1
Tampermonkey Scripts:
#1 Anti-Adblock Killer | Reek v9.8
#2 AdBlock Protector            v1.0.56

I have followed the instructions on https://x01x012013.github.io/AdBlockProtector/

However, the page still says -
# AdBlock Protector is not installed or not enabled!

Where am I going wrong? (Also, and I think it is related, the scripts don't help me on TimesOfIndia sites, which was the entire objective of the experimentation).

Thanks.

![page_response](https://cloud.githubusercontent.com/assets/11489601/17427556/3b2468c8-5aff-11e6-8b5c-def2ce557427.png)
![tampermonkey_scripts](https://cloud.githubusercontent.com/assets/11489601/17427558/3c015eae-5aff-11e6-8e74-d00b947d57e1.png)
![abp_options](https://cloud.githubusercontent.com/assets/11489601/17427559/3c04f4d8-5aff-11e6-8d15-5b3be0babb9e.png)

[Document1.pdf](https://github.com/X01X012013/AdBlockProtector/files/403198/Document1.pdf)

**Comment by rahulraj80** [comment]
Correction - reinstalling all addins (tampermonkey and adblock plus) and the scripts seems to have resolved the issue with TimesofIndia. I still am getting the red alert on the adblock protector home page though.

**Comment by X01X012013** [comment]
@rahulraj80 
The home page will try to re-define a read-only variable set by AdBlock Protector. Your web browser may allowed the variable to be re-defined where it should throw an error. Some websites will work fine without read-only limitation where others will need the read-only property to be enforced. 

I just tested the home page and it works fine on Opera and Chrome, it is an issue related to Safari.

**Comment by X01X012013** [comment]
Update: The installation check will now use `typeof` instead of `try catch`, which should be much more reliable. If anyone is still experiencing issues, please let me know.
