### ISSUE TITLE
techreviewpro.com

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#65]
![capture](https://cloud.githubusercontent.com/assets/15007183/23323309/0b7465b8-fab6-11e6-8dd2-9e08b0a2b0d9.PNG)

**Comment by uBlock-user** [comment]
add `techreviewpro.com##script:iject(noeval.js)`

or

add `@@||techreviewpro.com^$elemhide`

**Comment by X01X012013** [comment]
Hi, this website should be caught in our generic protectors. There could be a race condition, update the Script and let me know if it still blocks you.

**Comment by xxcriticxx** [comment]
yes somethign wrong here letme update and reboot

**Comment by xxcriticxx** [comment]
we still on different version with list and script?

script ver 6.49 and list ver 6.20

**Comment by xxcriticxx** [comment]
ok after reboot this website is good not but last.fm still detect ad block

**Comment by X01X012013** [comment]
OK, since it is good, I'll close this issue.
