### ISSUE TITLE
history.com

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#66]
http://www.history.com/shows/six/season-1/episode-6

ads dont play tv show dont play

**Comment by X01X012013** [comment]
The link sends me back to home page... Do you need to log-in or something to access it?

**Comment by xxcriticxx** [comment]
nope plays the ad first

![capture](https://cloud.githubusercontent.com/assets/15007183/23324358/4780df64-fabb-11e6-8607-e77296add4c2.PNG)

then tv show plays 

![capture1](https://cloud.githubusercontent.com/assets/15007183/23324361/50c5dd04-fabb-11e6-9761-17416f36567d.PNG)

if you REGISTER you can continue to watch where you left off

**Comment by xxcriticxx** [comment]
i be back in 1 h

**Comment by X01X012013** [comment]
It reliably kicks me back to home page. Do you have instructions on how to get to your page?

**Comment by xxcriticxx** [comment]
go to http://www.history.com/ on the main page click watch the latest episode 

![capture](https://cloud.githubusercontent.com/assets/15007183/23326229/ba43f30c-fac9-11e6-8368-28aff18ff978.PNG)

**Comment by X01X012013** [comment]
@xxcriticxx Ah, I see why... it redirected me to the Canadian website... Lemme tunnel to the States.

**Comment by X01X012013** [comment]
Well, the video starts directly for me... I'm not sure what's going on here... Are you sure your configuration is right? Because all your recent issues can't be reproduced. 
![image](https://cloud.githubusercontent.com/assets/7283682/23327216/4167edb6-fac5-11e6-9c3c-7fe501249730.png)

**Comment by X01X012013** [comment]
Let's handle this in #67
