### ISSUE TITLE
Filter configuration: crunchyroll.com, history.com, last.fm

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#67]
i get top menu only rest of the page is blank (i dont know if this is ad block or cookies)

![capture](https://cloud.githubusercontent.com/assets/15007183/23324267/bba19b5a-faba-11e6-890a-5b51159c932a.PNG)

**Comment by X01X012013** [comment]
Works for me... Do you have other filters or network level filters? 
![image](https://cloud.githubusercontent.com/assets/7283682/23324444/0d14d4da-faab-11e6-8bd2-a802e91c9b19.png)

**Comment by uBlock-user** [comment]
If you still have AAK script in TM,, remove it.

**Comment by xxcriticxx** [comment]
@uBlock-user i dont have aak anymore i clear all my ubo and browser and page still dont open with default lists. only opens up when i turn off ubo.

**Comment by X01X012013** [comment]
Do you have any custom rules in uBO? Did you touch default white list? It should be: 
```
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
loopconversation.about-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
```

**Comment by xxcriticxx** [comment]
no custom list only default filters and i did not touch white list i have all the once you listed here

**Comment by X01X012013** [comment]
I'll close this issue, let me know if you are still experiencing issues.
