### ISSUE TITLE
autokult.pl, wiadomosci.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#68]
http://autokult.pl/11192,co-slychac-na-facebooku-10-najlepszych-motoryzacyjnych-fanpageow-w-polsce

AdBlock Protector failed to find media ID with method 1! 

![capture](https://cloud.githubusercontent.com/assets/15007183/23333492/51290358-fb5a-11e6-98ba-838ed568f89f.PNG)

**Comment by xxcriticxx** [comment]
@szymon1118 please take look at this problem

**Comment by szymon1118** [comment]
@xxcriticxx We need to wait for @X01X012013 because most of these videos should work with 2nd grabbing method.

**Comment by X01X012013** [comment]
Another test URL: 
http://wiadomosci.wp.pl/kat,1342,title,Awantura-w-Sejmie-o-nowego-sedziego-Trybunalu-Konstytucyjnego,wid,18711700,wiadomosc.html

**Comment by xxcriticxx** [comment]
am going delete my browsing history + cookies see if this helps

**Comment by xxcriticxx** [comment]
that did not help

**Comment by X01X012013** [comment]
Fix in 6.54
Player container has different ID...

**Comment by xxcriticxx** [comment]
autokult works 
wp.pl doesn't

**Comment by X01X012013** [comment]
Ops... I was beautifying my code and apparently I broke something...

**Comment by X01X012013** [comment]
OK, fixed in 6.55.

**Comment by xxcriticxx** [comment]
yes sir works now

**Comment by X01X012013** [comment]
Alright, I'll close this issue now.
