### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#69]
something change at wp.pl getting ad block again

http://wiadomosci.wp.pl/grozny-wypadek-w-lukowie-kobieta-cofala-autem-i-potracila-92-latke-6094916946642049a

**Comment by X01X012013** [comment]
From source code, that page seems to be a pure block page, I clicked a random link from their home page, it seems to work... 
http://wiadomosci.wp.pl/kat,1342,title,Awantura-w-Sejmie-o-nowego-sedziego-Trybunalu-Konstytucyjnego,wid,18711700,wiadomosc.html

**Comment by xxcriticxx** [comment]
i get ad block all over same at your test link

![capture](https://cloud.githubusercontent.com/assets/15007183/23334536/07532faa-fb6f-11e6-9cb0-75de9d700121.PNG)

**Comment by X01X012013** [comment]
Let's handle this in #68

**Comment by X01X012013** [comment]
Update: Fixed in 6.53
