### ISSUE TITLE
htmlgames.com

### ISSUE THREAD

**Issue by applesam** [X01X012013/AdBlockProtector#7]
http://www.htmlgames.com/game/Cookie+Monster
and
http://www.mindgames.com/game/Brain+Workout

please fix this
![snapshot](https://cloud.githubusercontent.com/assets/20497954/17463484/21ef5eb2-5ce4-11e6-8cc8-3809766759b9.jpg)

**Comment by X01X012013** [comment]
Hi there, these websites will check if `google` is defined then show the block screen for 30 seconds, which makes loading a lot slower. Allowing Google SDK to load will not show ads since they will be blocked separately. 
Try these filters and see if you are still seeing the block screen: 
```
@@|http://imasdk.googleapis.com/js/sdkloader/$domain=htmlgames.com
@@|http://imasdk.googleapis.com/js/sdkloader/$domain=mindgames.com
```

**Comment by X01X012013** [comment]
It's been 5 days an there is no response, I assume this workaround works. Let me know if there are other issues.
