### ISSUE TITLE
YouTube AdBlock list 

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#72]
@X01X012013 need some help with youtube and host file wonder if you can make simple script that would catch new yt domains

**Comment by X01X012013** [comment]
What do you mean by YouTube domain? What criteria should the script match?

**Comment by xxcriticxx** [comment]
googles dns stoped blocking ads when you watch youtube. you need to play random vid and see if it send connection to *.googlevideo.com

**Comment by uBlock-user** [comment]
Must be a regional thing, I cannot reproduce any ads on Youtube.

**Comment by xxcriticxx** [comment]
you must use google as main dns and must be using host file no ubo installed 

here is current list:

https://raw.githubusercontent.com/HenningVanRaumle/pihole-ytadblock/master/ytadblock.txt.backup

**Comment by uBlock-user** [comment]
Try - `||$third-party,script,domain=youtube.com`

**Comment by xxcriticxx** [comment]
i am using host file for phones and tablets rest i have ubo

**Comment by X01X012013** [comment]
Ah, I see what you mean. So what logic do you need in the script?

**Comment by xxcriticxx** [comment]
@X01X012013 i have no idea yet i need quick way to catch as many *.googlevideo.com as possible

**Comment by X01X012013** [comment]
It would be XHR request? How do you want to log it? A `prompt`? Is it OK to block access when collecting data?

**Comment by X01X012013** [comment]
Also, I bet they randomize it now and then... Did you try FireFox for Android? You can have uBO plug-in on that.

**Comment by xxcriticxx** [comment]
yes they radomize it :) i have iphone and ipads.

**Comment by X01X012013** [comment]
OK, then Userscript alone might not work. You may want a PHP server for callback and do automated analysis. You can't fight automated process by hand... 
Logging all XHR request to `*.googlevideo.com` is easy, you can just use uBO to do it, but I bet that isn't what you are looking for. I still don't know what kind of logic you are looking for, can you provide some pseudocode?

**Comment by xxcriticxx** [comment]
i can look it up in my pihole server

**Comment by X01X012013** [comment]
Can you explain in detail what are you looking for?

**Comment by xxcriticxx** [comment]
@X01X012013 i dont know what am looking for need quick way to check if vid conenct to googlevideo.com and if does log it in txt file

**Comment by X01X012013** [comment]
Didn't you just said access log can be looked up in Pi Hole?

**Comment by xxcriticxx** [comment]
yes but i have to watch the whole vid and wait for ads to show up

**Comment by xxcriticxx** [comment]
i am looking for quick way to generate list

**Comment by X01X012013** [comment]
Oh... I see what you mean... have you looked into PhantomJS?

**Comment by X01X012013** [comment]
I have to say what you are looking for isn't doable with Userscript... Maybe it is, but very hard and inefficient. Use a headless bot will make more sense.

**Comment by xxcriticxx** [comment]
ok got it thx for help
