### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#78]
@X01X012013 i think you should look in replacing player on yt because ads are starting to trickle down

**Comment by X01X012013** [comment]
I don't see any ads. 

There is no easy way to replace YouTube player, that player is quite complex and loads video chunk by chunk, instead of one big file.

**Comment by xxcriticxx** [comment]
give couple for days lets see what happens

**Comment by X01X012013** [comment]
I still don't see any ads.

**Comment by HateAds** [comment]
@jspenguin2017 https://www.o2.pl/short/hiszpanskiemu-plywakowi-odmowiono-minuty-ciszy-po-zamachu-zobacz-co-zrobil-6157530797786753s
The YouTube player keep disappearing on this site. ( It's happening when ublock protector extension is enabled )
UPE enabled 
![image](https://user-images.githubusercontent.com/29756590/29537741-201cd86c-86c3-11e7-8d14-09feb41bdb2e.png)
UPE disabled
![image](https://user-images.githubusercontent.com/29756590/29537768-4080fcf0-86c3-11e7-8633-f2115a3d4eff.png)

**Comment by jspenguin2017** [comment]
Fixed. But that is off topic here, report it to an appropriate thread next time.
