### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#79]
see i am not the only one who gets ad block on that page

https://github.com/reek/anti-adblock-killer/issues/2901

**Comment by X01X012013** [comment]
Yes but he is using AAK.

**Comment by xxcriticxx** [comment]
an am not and i still have ad block msg

**Comment by X01X012013** [comment]
I just can't reproduce this. Here are my activated filters: 
![image](https://cloud.githubusercontent.com/assets/7283682/23531126/20c865bc-ff62-11e6-82cf-fdae9b04b780.png)

**Comment by xxcriticxx** [comment]
I will share my list tomorrow

**Comment by uBlock-user** [comment]
try - `last.fm##script:inject(last.fm.js)`

**Comment by xxcriticxx** [comment]
here is my list:

![capture](https://cloud.githubusercontent.com/assets/15007183/23554013/4968c6b2-fff1-11e6-8f04-c490e7d93ed7.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15007183/23554015/4b4f6b98-fff1-11e6-90ff-7ed9941b0da6.PNG)

**Comment by xxcriticxx** [comment]
@uBlock-user same with your fileters i try to clear history and cookies still get ad block popup on the bottom

**Comment by uBlock-user** [comment]
Activate all other unchecked filters except for MULTIPURPOSE category, see if that works.

**Comment by X01X012013** [comment]
Check Adblock Warning Removal List.

**Comment by xxcriticxx** [comment]
@X01X012013 checking adblock removal list did nothing for me still get msg

**Comment by X01X012013** [comment]
Can you try to configure your AdBlocker exactly like mine? It is possible that one of your custom list is outdated.

**Comment by xxcriticxx** [comment]
@X01X012013 i config ubo same as your i clear browser and still got msg

**Comment by X01X012013** [comment]
I can't reproduce this. Try these rules: 
```
@@||$xmlhttprequest,domain=last.fm
@@||adsensecustomsearchads.com/adsense/$script,domain=last.fm
@@||securepubads.g.doubleclick.net$script,domain=last.fm
```

**Comment by xxcriticxx** [comment]
nope i think i tried them already

**Comment by xxcriticxx** [comment]
console shows am blocking google that cant be good

<details>
![capture](https://cloud.githubusercontent.com/assets/15007183/23570794/eae4776a-0033-11e7-83cb-b8ac7de60390.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15007183/23570798/edbffab8-0033-11e7-960f-e93250698c14.PNG)
</details>

**Comment by X01X012013** [comment]
Looks like you have something else blocking the network traffic, which browser is that? 

![image](https://cloud.githubusercontent.com/assets/7283682/23570970/06800648-0024-11e7-96e7-2454ac7471a8.png)

**Comment by xxcriticxx** [comment]
chrome

**Comment by X01X012013** [comment]
Do you have other plug-ins that could block network traffics?

**Comment by xxcriticxx** [comment]
nope i test in ie with out any plugins and work like charm has to be some type of filter combination

**Comment by X01X012013** [comment]
This is an issue on your side, unfortunately, I am not able to help you in this case.
