### ISSUE TITLE
indiatoday.intoday.in

### ISSUE THREAD

**Issue by ashutoshgoyal** [X01X012013/AdBlockProtector#8]
http://indiatoday.intoday.in/olympics2016/story/rio-2016-vijay-goel-sports-minister/1/738449.html
Site showing adblock warning again.

**Comment by X01X012013** [comment]
Thanks for letting me know, the fix is patched into 1.0.68

`setReadOnly("adBlock", false);`

**Comment by X01X012013** [comment]
It's been 5 days and no update, I assume the fix worked. I will go ahead and close this issue.
