### ISSUE TITLE
chocianow.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#80]
http://www.chocianow.com.pl/mapa_chocianowa/

![capture](https://cloud.githubusercontent.com/assets/15007183/23530306/2ce8131c-ff6f-11e6-921f-c2ea448bccd5.PNG)

**Comment by X01X012013** [comment]
We have generic protector against Better Stop Adblock. Please make sure Script is properly installed and enabled. 
I could not reproduce this issue. 
![image](https://cloud.githubusercontent.com/assets/7283682/23531220/a9ea68e0-ff62-11e6-8a64-e6596135ab79.png)

**Comment by xxcriticxx** [comment]
I will test tomorrow sorry my friend

**Comment by xxcriticxx** [comment]
page is good script was off for testing
