### ISSUE TITLE
change list and script to same version 

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#81]
please :)

**Comment by X01X012013** [comment]
I did think about this, but then every time I update Script, the List will have its version changed, which will make AdBlockers re-download List for nothing. And we will need to change the current compiler setup to implement this. 
Thanks for your suggestion, but for now, we'll keep it as-is.

**Comment by uBlock-user** [comment]
and what does it change ? I don't see any advantage in doing that.

**Comment by xxcriticxx** [comment]
easier to track
