### ISSUE TITLE
NSFW! xnxx.com

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#82]
Cookie based popunder is fired when playing via HTML5 player. It will check for a cookie named ~~`wpn-popunder`~~ `wpn-popupunder` and if it is not present a popunder will be fired. Popunder code is mixed with the player so it cannot be directly blocked.

test case - http://www.xnxx.com/video-f42rld6/italian_pornstar_with_big_tits_fucked_hard_on_the_sun

Popunder code - http://static-hw.xvideos.com/v-2a5d7651e9f/v3/js/skins/min/player.html5.static.js

**PS** - If you have flash, then flash player will load and the popunder will load but that can be patched via `xnxx.com##script:inject(noeval.js)`

**Comment by X01X012013** [comment]
Did you found a way to grab the URL of the media file? We can just replace the player if we have that.

**Comment by uBlock-user** [comment]
[](https://i.gyazo.com/ade772b090bcad5f0740d44bd66b3451.png)

**Comment by X01X012013** [comment]
I meant grabbing URL with script. Anyway, looks like the player is loading multiple files, so we can't replace it.

**Comment by X01X012013** [comment]
We would need a way to grab the URL from Script.

**Comment by uBlock-user** [comment]
> grabbing URL with script

How do you mean exactly ?

Can't you patch it like you did with `pornhub.com` and others ?

**Comment by X01X012013** [comment]
Hum... Yea, we can try that. I'll have a look when I have time.

**Comment by szymon1118** [comment]
If you are still interested in grabbing videos from above sites it's easy: `window.open(html5player.url_high).focus()`

**Comment by X01X012013** [comment]
@szymon1118 
Wow nice! I'll see if there is an simpler way, that will be our ultimate solution.

**Comment by X01X012013** [comment]
Looks like it's a pop-up instead of pop-under, it doesn't go through `open()`. How about just locking the cookie? If they start to change the name of the cookie we'll respond with replacing their player.

**Comment by X01X012013** [comment]
OK, I locked the cookie. Not sure how long will this fix last. If it turns out that they change the name of the cookie often, then we'll use our next solution.

**Comment by uBlock-user** [comment]
Not a favourable solution since we're giving in their cookie game, but will do at the moment. Can you not patch `window.openpop` since it's using that for triggering the popup

**Comment by X01X012013** [comment]
@uBlock-user No, because their code abuses the real mouse event and the pop-up doesn't go through `open()`

**Comment by uBlock-user** [comment]
Well can the mouse event be patched ?

**Comment by X01X012013** [comment]
@uBlock-user Probably...

**Comment by uBlock-user** [comment]
Try it if you can, I tried killing `cookieCheck` by making it readOnly and tried NoAccess, didn't work. I will try few other tricks I can think and then I will leave it at that.

**Comment by X01X012013** [comment]
Well, `a.readOnly()` and `a.noAccess()` only work for global variables, if their function is defined only in a closure, there is no way to patch it.

**Comment by uBlock-user** [comment]
What about `window.wpn_categories` and/or `window.openpop`  ? Can one of these be killed ?

**Comment by X01X012013** [comment]
Yep, that does work 😄 
Next time I should check keywords from `window`'s properties. 
Note: Run this in console to dump `window`'s properties: `JSON.stringify(Object.keys(window));`

**Comment by uBlock-user** [comment]
I had a feeling that one of those should patch it. Finally.

**Comment by lain566** [comment]
@jspenguin2017  Can we use the same rule for `xvideos.com` and `xvideos.works` ?
this cookie `wpn-popupunder` is on these websites




test link
http://www.xvideos.com/video5061155/nerd_girlfriend_talks_sex_and_fingers_upskirt_in_stairwell
http://www.xvideos.works/video5061155/nerd_girlfriend_talks_sex_and_fingers_upskirt_in_stairwell



`xvideos.com##.sponsor-popup`
https://user-images.githubusercontent.com/27441315/27887954-ac354af0-61e3-11e7-8f04-c88e89d35c09.png

**Comment by jspenguin2017** [comment]
Added. The "sponsor popup" div is to be reported to EasyList.
