### ISSUE TITLE
sidereel.com

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#83]
@uBlock-user
> FYI - `sidereel.com` is acting up again today. I'm using `sidereel.com##script:inject(abort-on-property-read.js, setTimeout)`. It does break one or two things, however nothing major.

**Comment by X01X012013** [comment]
I'll see if we can use `a.filter()` to not break things.

**Comment by X01X012013** [comment]
@uBlock-user 
I can't reproduce the issue on the home page, can you check if some of your other filters may interfere with this website?

**Comment by ghajini** [comment]
It does things randomly......
See here 
`https://github.com/AdguardTeam/AdguardFilters/issues/4143`
allmusic.com issue is related to sidereel.com also.
`https://github.com/AdguardTeam/AdguardBrowserExtension/issues/512`

**Comment by X01X012013** [comment]
Ah... That explains... OK, I'll have another look.

**Comment by uBlock-user** [comment]
@X01X012013 I can always reproduce and even before, I believe patching `allmusic.com` might have created a side effect back then which was probably the reason you couldn't reproduce before, but now that's not the case. I do not have any filters related to `sidereel.com` so there's no interference on my end.

**Comment by uBlock-user** [comment]
@X01X012013 Running `JSON.stringify(Object.keys(window));` gives up an interesting list, might help patch this one too ?

**Comment by X01X012013** [comment]
Hum... `__rnd`... I'll have a look.

**Comment by uBlock-user** [comment]
tried `a.noAccess` and `a.readOnly` on that, no change.

**Comment by X01X012013** [comment]
Hum, looks like we'll need `a.protectFunc()` for this one... 
![image](https://cloud.githubusercontent.com/assets/7283682/23588626/7a37c71a-017d-11e7-809b-86df16ac5b8c.png)

**Comment by uBlock-user** [comment]
Can `a.protectFunc()` kill it ? Also can we set the value of `navigator.cookieEnabled` via a userscript ?

**Comment by X01X012013** [comment]
I think this should work: 
```JavaScript
if (a.domCmp(["sidereel.com"])) {
    //Protect functions then activate filter on setTimeout()
    a.protectFunc();
    a.filter("setTimeout", /function \_0x[a-z0-9]{4,8}\(\)\{try\{var/);
}
```
I added to 6.79

**Comment by uBlock-user** [comment]
No change at all.

**Comment by X01X012013** [comment]
I posted the message before I committed the change... And it will take a moment for GitHub to update the file it serves.

**Comment by uBlock-user** [comment]
I already updated and version 6.79 is here along with the code you posted. Everything's done and I tested by removing all existing cookies and hitting a Refresh, the result is same.

**Comment by uBlock-user** [comment]
The only thing that remotely works is `a.noAccess("setTimeout")` which I mentioned before breaks few things here and there or BLOCK cookie creation via the browser.

**Comment by X01X012013** [comment]
Hum... Do you have a specific test link? I tried on home page and a few random links, nothing. 
I think we can use `Object.defineProperty` to set `navigator.cookieEnabled`...

**Comment by uBlock-user** [comment]
No specific links. For me, it happens on the home-page itself. I only have uBO and VM enabled.

>  think we can use Object.defineProperty to set navigator.cookieEnabled

Are you sure ? I googled a lot and couldn't find anything that can set that value.

**Comment by X01X012013** [comment]
You are right, that property seems to not be editable. It doesn't throw error, but when you `get` it, it returns `true` or `false` depending on the browser's settings.

**Comment by X01X012013** [comment]
Can you try to install List? That could be the reason I can't reproduce it.

**Comment by uBlock-user** [comment]
So what are we going to do ?

**Comment by uBlock-user** [comment]
Nope, no change, only 15 filters were added and none of them had anything to do with `sidereel.com`

**Comment by X01X012013** [comment]
> So what are we going to do ?

What do you mean? We can't change `navigator.cookieEnabled`, we just can't.

**Comment by uBlock-user** [comment]
> What do you mean?

We're stuck here, so what do we do from here on ? Call off the search for a solution or keep looking ?

**Comment by X01X012013** [comment]
I think this website is fixed by EasyList, are you sure you don't have any conflicting filters? I visited it quite a few times already, and I haven't seen the block screen once.

**Comment by uBlock-user** [comment]
> are you sure you don't have any conflicting filters?

Can you list the thing that are blocked on your end ?

**Comment by X01X012013** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/23589694/fc3f3d4a-018e-11e7-9a8e-075987073a57.png)
![image](https://cloud.githubusercontent.com/assets/7283682/23589695/02b10f00-018f-11e7-8284-038a1e808316.png)
![image](https://cloud.githubusercontent.com/assets/7283682/23589698/10c9f98a-018f-11e7-95bd-d2631001341b.png)

**Comment by X01X012013** [comment]
Can you try this rule? (It's slightly different than the one before)
```JavaScript
if (a.domCmp(["sidereel.com"])) {
    a.protectFunc();
    a.filter("setTimeout", /function \_0x[a-z0-9]{4,8}\(/);
}
```

**Comment by uBlock-user** [comment]
That's working !! Wow, seems you finally did it. Was only able to reproduce once out of 8 trials. probably because of race condition.

**Comment by uBlock-user** [comment]
That also patches `allmusic.com` FYI

**Comment by X01X012013** [comment]
Yea, the race condition, there is no guarantee that my code will run before theirs. Chrome loves speed, and sometimes it's too fast... A refresh will fix it, since refresh forces Chrome to reload from source and not restore a cached snapshot. 
I'll keep `$inline-script` for `allmusic.com` since that is more stable. I'll add this rule to Script.

**Comment by uBlock-user** [comment]
It's fine though, only happened once. I haven't been able to reproduce it again. Works perfectly as intended.

**Comment by X01X012013** [comment]
Good. I'll close this issue now.

**Comment by jspenguin2017** [comment]
Looks like this is patched in uBlock filters, I'm removing it from Script. The extension will have some slight problems when it comes to scoping so patching `Function.prototype.toString` must be done manually from now on. It's used precisely 0 times after removing this filter.
