### ISSUE TITLE
fotoblogia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#84]
only me with ad block on this page?

http://fotoblogia.pl/10356,world-press-photo-2017-czy-mamy-do-czynienia-z-kolejnym-oszustwem-i-ustawianym-fotoreportazem

**Comment by X01X012013** [comment]
This is fixed by List 6.27 and Script 6.73.

**Comment by uBlock-user** [comment]
Not fixed, I can reproduce it.

**Comment by uBlock-user** [comment]
This should kill it for the time being - `fotoblogia.pl##script:inject(overlay-buster.js)`

**Comment by X01X012013** [comment]
Did you update List? I added a generic rule `###like-us-adblock-modal`.

**Comment by uBlock-user** [comment]
I only use UserScript and not the List. I thought you patched in the UserScript. Nevermind.

**Comment by X01X012013** [comment]
Looks like this is good, I'll close this issue now.
