### ISSUE TITLE
fox.com

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#87]
this from reeks repo

test link:

http://www.fox.com/watch/884936771556/7833474048

@uBlock-user what your location that you can't reproduce? i get them with us nyc ip 
@X01X012013 can you reproduce?

btw this works https://forums.lanik.us/viewtopic.php?f=62&t=35593&p=113749&hilit=fox.com#p113749

**Comment by uBlock-user** [comment]
Location has nothing to do with it. Mine simply doesn't detect being adblocked for some reason.

I rather get this - `Sorry, there was a problem accessing your video.
Please see this support document for help in resolving the issue.`

**Comment by xxcriticxx** [comment]
did this pop out on the first time? http://i.imgur.com/R2X8drI.png

**Comment by X01X012013** [comment]
@xxcriticxx That is not a pop-up, it's part of the HTML. It's asking if you want to receive notification, if you click allow, your browser will ask you again. 

I don't see this in AAK repo, can you link it? 

Also, I am getting Geo Lock message here in Canada.

**Comment by uBlock-user** [comment]
Nope, I block all unnecessary 3rd party connnections, so I never saw that.

**Comment by xxcriticxx** [comment]
when you click on don't allow msg about ad block pop up right away

**Comment by uBlock-user** [comment]
This is what happens on my end - https://i.gyazo.com/367d1b0d88f36a6139980b0242d04115.png

**Comment by X01X012013** [comment]
Hi, after thinking about this, I think blocking notification dialogue isn't in the scope of this project. It might not be the behavior that everyone wants, so please add the filter to your AdBlocker yourself. 
I don't see any AdBlock detection block screen, but rather Geo Lock screen: 
![image](https://cloud.githubusercontent.com/assets/7283682/23754672/1253dbc2-049b-11e7-8f9b-c9b49c3dcecb.png)

**Comment by uBlock-user** [comment]
@X01X012013 Use DataSaver Extension and see if you can reproduce that GeoLock again.

**Comment by X01X012013** [comment]
What? Why? That's not part of standard configuration...

**Comment by uBlock-user** [comment]
I just want to see if it specifically catches IPs of a country or if it's simply isn't working on my end. Nevermind though, without DS, the situation is still the same on my end.

**Comment by X01X012013** [comment]
I don't see any problem except Geo Lock, which is not in the scope of this project. Since there is no update for 4 days, I'll close this issue now.

**Comment by ghajini** [comment]
test link
https://www.fox.com/watch/2046d8741d77ef3febfb6004f68a55f2/

i got this problem.....
***video is paused***
![chrome_2017-10-08_13-42-22](https://user-images.githubusercontent.com/20338483/31315118-346dfc88-ac2f-11e7-813e-2e4adf4bd3f5.png)


...and if easylist filters are used mentioned in thread preroll ad is shown

**Comment by jspenguin2017** [comment]
It tries to destroy ads manager without checking if it has it at all. I'll just block the SDK.

**Comment by ghajini** [comment]
i see preroll ads
![chrome_2017-10-08_17-41-46](https://user-images.githubusercontent.com/20338483/31319289-30baab3c-ac7e-11e7-9bb1-097676448c96.png)
may be they are fired by uplynk as per ubo logger

**Comment by jspenguin2017** [comment]
The preroll is not caused by uBlock Protector isn't it?

**Comment by ghajini** [comment]
@mapx- can you try ublock origin+ublock protector.....iam getting preroll ad ,may /may not be caused by easylist whitelist filter

**Comment by jspenguin2017** [comment]
It is not caused by uBlock Protector, so report to EasyList first. 
![image](https://user-images.githubusercontent.com/7283682/31319577-2a0e8fa2-ac23-11e7-9807-e6d3c7448a29.png)

**Comment by lain566** [comment]
Easylist does not have the solution, and I don't think uBO/uAssets has it, either.

**Comment by jspenguin2017** [comment]
Well... My VPN is used up for this month, got to wait for the next.
