### ISSUE TITLE
tune.pk

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#92]
https://tune.pk/video/6978566/geostorm-2017-official-teaser-trailer-1-ft-katheryn-winnick-gerard-butler

![capture](https://cloud.githubusercontent.com/assets/15007183/23825626/1c8e4c46-065b-11e7-9866-6c6b208deac5.PNG)

**Comment by uBlock-user** [comment]
Lock `ad_blocker` in the script.

**Comment by X01X012013** [comment]
Doesn't work. Let's just block the block screen. `tune.pk###annoy-wrapper`

**Comment by xxcriticxx** [comment]
after that you got 10 sec add that you dont see but have to wait

**Comment by uBlock-user** [comment]
I cannot reproduce. Most probably patched as `googletag` remains undefined due uBO's experimental filter which breaks the detector I guess.

**Comment by xxcriticxx** [comment]
there is 10 sec black screen till the video starts

**Comment by uBlock-user** [comment]
add - `||player.tune.pk/v2/js/annoy.min.js^` That one is from Adguard' FilterList, that's why I cannot reproduce.

**Comment by xxcriticxx** [comment]
i am still waiting on something in the blakc screen

**Comment by xxcriticxx** [comment]
both filters work

**Comment by X01X012013** [comment]
If you click the play button on the lower left, the video plays immediately.

**Comment by xxcriticxx** [comment]
yep i call this fixed

**Comment by X01X012013** [comment]
Good. I'll close this issue now.
