### ISSUE TITLE
NSFW! czechhq.net

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#93]
https://github.com/reek/anti-adblock-killer/issues/2946

**Comment by X01X012013** [comment]
Popup fixed. 

Notes for devs: 
Triggers generic protector against FuckAdBlock. 
Video domain is `29443kmq.video`.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2946#issuecomment-286061584

Same as `vidlox.tv` which is already present in your script, just add the domain `29443kmq.video`

**Comment by X01X012013** [comment]
Awesome! Added to Script.

**Comment by X01X012013** [comment]
I also added `29443kmq.video###a` to List so play and pause goes smoother.

**Comment by uBlock-user** [comment]
Thanks, works fine as intended. You may close the issue now.

**Comment by raymonders** [comment]
Tried clicking on random video links. Not working 2/3 of the time:
problems seen:
video box is greyed out, with no message
or
video box is white with "disable adblock" message
or 
play button appears, but clicking does not start video

**Comment by X01X012013** [comment]
I replied you in the other thread: 

> Sometimes the video that should be replacing the gray box doesn't load, but the player right below it works. I can't remove the gray box since sometimes it works. Out of a couple random links I clicked, at least one video player works. If you have a specific test link where nothing works, please post it.

Also, please make sure AdBlock Protector is properly installed.

**Comment by X01X012013** [comment]
They are back with new popunders. 
Sometimes AdBlock detection block screen can be triggered due to race condition.

**Comment by uBlock-user** [comment]
> They are back with new popunders.

That's probably from new third party domains, I'm blocking all third party connections by default, so I'm not getting any popunders. Secondly, popads is patched by uBO Filters, so let them update their code as much as they want, won't bother us. 

Now coming to the race condition, I'm facing that too, this wasn't happening that day, I wonder if they changed the position of the code and yes videos are largely no playing from the beginning for whatever reason if I fast forward they do play then.

**Comment by uBlock-user** [comment]
Domain `29443kmq.video` has been redirected to `dato.porn` so add that domain too.

**Comment by X01X012013** [comment]
@uBlock-user OK, I have updated Script to counter the new domain. For List, which rule did you use? I tried these but they don't seem to work... 
```
||czechhq.net^$third-party
@@||29443kmq.video^$domain=czechhq.net
@@||datoporn.com^$domain=czechhq.net
@@||dato.porn^$domain=czechhq.net
```

**Comment by uBlock-user** [comment]
add these 
````
29443kmq.video,dato.porn###a
||$third-party,domain=czechhq.net
@@||fonts.googleapis.com^$domain=czechhq.net
@@||pixhost.org^$image,domain=czechhq.net
@@||wordpress.org^$domain=czechhq.net
@@||29443kmq.video^$domain=czechhq.net
@@||dato.porn^$domain=czechhq.net
````

**Comment by X01X012013** [comment]
@uBlock-user Awesome! Thanks.

**Comment by ghajini** [comment]
soo!!! many exceptions right?
Do you any other solution other than exceptions

**Comment by uBlock-user** [comment]
I can simmer down the exceptions by modifying the filters if you want.

```
29443kmq.video,dato.porn###a
||$third-party,domain=czechhq.net
@@||$stylesheet,image,font,media,domain=czechhq.net
```

**Comment by ghajini** [comment]
Then these filters by @mapx- are narrow then

|http://$xmlhttprequest,third-party,domain=czechhq.net
@@||29443kmq.video/js/pop.js
||datoporn.co^$popup
29443kmq.video###center-ad
@@||streamdefence.com/view.php?*$domain=czechhq.net
||openload.co/*license
||openload.co/*script

**Comment by ghajini** [comment]
Then these filters by @mapx- are not that broad.....
`|http://$xmlhttprequest,third-party,domain=czechhq.net`

`@@||29443kmq.video/js/pop.js`

`||datoporn.co^$popup`

`29443kmq.video###center-ad`

`@@||streamdefence.com/view.php?*$domain=czechhq.net`

`||openload.co/*license`

`||openload.co/*script`

**Comment by uBlock-user** [comment]
Those don't stop the 3rd party popups/popunders, they close it, there's a difference. Popunders will try to open and will be closed in a flash still. If you're okay with it, then use them.

**Comment by X01X012013** [comment]
@ghajini I don't see the problem there, the exceptions would be loaded if you don't use the first rule. And the 2nd solution is allowing more content by filtering by type.

**Comment by X01X012013** [comment]
Since there is no feedback for 6 days, I assume this issue is resolved. Please let me know if there are any problems.
