### ISSUE TITLE
Filter List issue?

### ISSUE THREAD

**Issue by raymonders** [X01X012013/AdBlockProtector#94]
Clicking on Filter List link on "https://x01x012013.github.io/AdBlockProtector/" redirects to AAK page, and gives this error message.

![problem](https://cloud.githubusercontent.com/assets/21112692/23876621/a3ea153c-083e-11e7-982d-a65b1368a640.JPG)

**Comment by X01X012013** [comment]
Hi, List currently only support uBlock Origin.

**Comment by uBlock-user** [comment]
Remove Adblock and install uBlock Origin.
