### ISSUE TITLE
mooseroots.com

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#96]
http://names.mooseroots.com/

Scroll down the page a bit and the overlay will appear.

**Comment by xxcriticxx** [comment]
i can’t reproduce the issue

**Comment by uBlock-user** [comment]
That's probably because you must a white-listing filter for an XHR from the domain.

**Comment by X01X012013** [comment]
OK, I'll have a look.

**Comment by uBlock-user** [comment]
This is how it looks like - https://i.gyazo.com/a3de0b9b15996658905839cfaccd540e.png

**Comment by X01X012013** [comment]
Fixed with important style. Added to Script.

**Comment by uBlock-user** [comment]
Works Perfectly! There are few domains which also run the same script. One of them is `insidegov.com`,  I will list more as I come across.

**Comment by X01X012013** [comment]
OK, added to Script.

**Comment by uBlock-user** [comment]
You may close the issue though.

**Comment by uBlock-user** [comment]
List - https://github.com/uBlockOrigin/uAssets/issues/573

**Comment by jspenguin2017** [comment]
Since it is taken care of by uBlock filter, I'll just remove the script rule...
