### ISSUE TITLE
`Redirect:` field [Question]

### ISSUE THREAD

**Issue by Alex-302** [X01X012013/AdBlockProtector#97]
@X01X012013 What is the purpose of this string in the filter?
`! Redirect: https://github.com/X01X012013/AdBlockProtector/raw/master/AdBlockProtectorList.txt`

**Comment by X01X012013** [comment]
This is the download URL of List.

**Comment by Alex-302** [comment]
But why do you need it?)
When you open https://github.com/X01X012013/AdBlockProtector/raw/master/AdBlockProtectorList.txt
it's obvious that the URL is download link:)

**Comment by X01X012013** [comment]
I know it's not needed, but I have it there in case someone open the file from uBO and want to know where it is from. The URL is not in the address bar when it is opened from uBO.

**Comment by Alex-302** [comment]
> The URL is not in the address bar when it is opened from uBO

But user can go to homepage
`! Homepage: https://x01x012013.github.io/AdBlockProtector/`

I can't add your filter to Adguard, because `Redirect:` is processed and we get infinite loop:(

**Comment by X01X012013** [comment]
From https://adblockplus.org/filters : 
> This comment is ignored if the new address is the same as the current address, meaning that it can be used to enforce the "canonical" address of the filter list.

Looks like it's a bug in Adguard.

**Comment by X01X012013** [comment]
BTW what the first line should be doesn't have official rule, I have `[uBlock Origin]` since we have are using uBO extended syntax. https://adblockplus.org/faq_internal#filtersfile

**Comment by Alex-302** [comment]
> Looks like it's a bug in Adguard.

In general - yes.. Ok, will wait for the fix.

```
tvn.pl#div(id*=_videoDriverContent)
```
invalid selector

**Comment by X01X012013** [comment]
That line is from examples here: https://adblockplus.org/forum/viewtopic.php?t=697
Also, I changed the header. Our filter doesn't work in ABP, there is no reason to follow their header format. It is now using uBO header format.

**Comment by Alex-302** [comment]
Ok, got it.
