### ISSUE TITLE
fmovies.to

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#99]
Launches cookies based popups.

Popup script - http://pastebin.com/raw/AAhE2MRf

Some key facts fyi -

- Killing `eval` will break the CSS and possibly the player.

- I have tried patching via the var `m6w2` which is a random var and they keep changing it to evade, it worked till now however patching it NOW also breaks the CSS.

- Blocking all site cookies stop the script from functioning, however the user won't be able to login.

- We need a persistent solution as the website notoriously likes to evade filters.

**Comment by uBlock-user** [comment]
Nevermind, blocking `7636ca6cb9fc.com` entirely breaks the script.

**Comment by uBlock-user** [comment]
After much lengthy investigation, I conclude that following solutions work and complement each other.

````javascript
if (a.domCmp(["fmovies.to", "fmovies.se", "fmovies.is"])) {
    a.win.open = function () { };
}
````

Patching `win.open` kills the popup when cookies are cleared and you're browsing as a guest and when this page - `http://fmovies.to/news/blog` is opened. This is cookie based as long as cookies stay the popup won't appear.

The second solution would be to block this random third-party domain - `7636ca6cb9fc.com` That one loads a CSS and a JS which fires popups when you're logged in and not browsing as a guest. This domain does look random so blocking third-party scripts would be advisables for `fmovies.*`

**Comment by X01X012013** [comment]
Awesome, I'll add them to List and Script. The problem is `7636ca6cb9fc.com` looks pretty temporary...

**Comment by uBlock-user** [comment]
> The problem is 7636ca6cb9fc.com looks pretty temporary...

Yes it does, that's why I'm blocking all third party content and creating exceptions wherever needed.

**Comment by uBlock-user** [comment]
If you don't block the domain, it will be reported on Easylist soon enough and will get blocked, but the important part is patching inline-popups through `window.open`, that patch needs to be added first and foremost.

**Comment by X01X012013** [comment]
Hi, your fix is added to Script and List. Thanks for your contribution.

**Comment by uBlock-user** [comment]
Closing the issue then, thanks.

**Comment by uBlock-user** [comment]
New popup shenanighans from this script -

```javascript
(function (doc, adBlockHandlerName, adBlockLocation) {
    window[adBlockHandlerName] = function() {
        var load = function load() {
                var xhr = new XMLHttpRequest();
                xhr.withCredentials = true;
                xhr.open('GET', adBlockLocation, true);
                xhr.onreadystatechange = function () {
                    if (xhr.readyState == 4 && xhr.status == 200 && xhr.responseText) {
                        eval(xhr.responseText);
                    }
                };
                try {
                    xhr.send();
                } catch (e) {
                    try { console.error('Unable to load antiadblock code'); } catch(e) {}
                }
        };
        load();
    };
})(window.document, 'hahaadblock', '/804548.hahaadblock'); 
```

**Comment by uBlock-user** [comment]
Filter - fmovies.*##script:inject(abort-on-property-read.js, hahaadblock)

or

Filter - fmovies.*##script:inject(abort-on-property-read.js, XMLHttpRequest)

**Comment by uBlock-user** [comment]
I wonder if we can kill this specific eval here with `noeval-if.js` as these guys tend to use `eval` for popups

**Comment by jspenguin2017** [comment]
Probably, but can't be generic.

**Comment by uBlock-user** [comment]
`fmovies.*##script:inject(noeval-if.js, xhr.status == 200)`

Will that work ? I can't reproduce it with that one.

**Comment by jspenguin2017** [comment]
For this domain yea, but not for others.

**Comment by uBlock-user** [comment]
Ofcourse I was only asking for this domain.

**Comment by jspenguin2017** [comment]
Well, there are many ways to fix it, if that works, then that's another solution.
